---
title: "plot_GSEA"
output: html_document
date: "2024-06-03"
---

```{r}
rm(list = ls())
```



```{r}
pv = "0.000001"
root_fold = "/Volumes/shladysh/scMINER/figures/CROP_Seq_GRN_evaluation/Gersbach"
save_fold = "/Volumes/shladysh/scMINER/figures/CROP_Seq_GRN_evaluation/Gersbach/results"
```


```{r}
filt_inp_file = "/Volumes/shladysh/scMINER/figures/CROP_Seq_GRN_evaluation/Gersbach/data/filt_targets_results.Rdata"
load(filt_inp_file)

load(file.path(root_fold, "data", paste("GSEA_results_pv_", pv, ".Rdata", sep = "")))
```


```{r}
options(scipen = 0)
options(digits = 2)

smpl = "D1_a"
gene = "BATF3"
rank_profile = GSEA_scMINER[[smpl]][[gene]]$pos$r_p
df <- data.frame(rank_profile = GSEA_scMINER[[smpl]][[gene]]$pos$r_p,
                 scMINER_pos = GSEA_scMINER[[smpl]][[gene]]$pos$RES,
                 scMINER_neg = GSEA_scMINER[[smpl]][[gene]]$neg$RES,
                 GRNBoost2 = GSEA_GRNB2[[smpl]][[gene]]$all$RES,
                 GENIE3 = GSEA_GN3[[smpl]][[gene]]$all$RES,
                 PIDC = GSEA_PIDC[[smpl]][[gene]]$all$RES, 
                 pos = 1:length(GSEA_scMINER[[smpl]][[gene]]$pos$r_p))

ids_pos = which(GSEA_scMINER[[smpl]][[gene]]$pos$indicator == 1)
ES_pos = abs(GSEA_scMINER[[smpl]][[gene]]$pos$RES[ids_pos])
data_pos <- data.frame(x = ids_pos, ES = ES_pos)

ids_neg = which(GSEA_scMINER[[smpl]][[gene]]$neg$indicator == 1)
ES_neg = abs(GSEA_scMINER[[smpl]][[gene]]$neg$RES[ids_neg])
data_neg <- data.frame(x = ids_neg, ES = ES_neg)

ids = which(GSEA_GRNB2[[smpl]][[gene]]$all$indicator == 1)
ES = abs(GSEA_GRNB2[[smpl]][[gene]]$all$RES[ids])
data_GRNB2 <- data.frame(x = ids, ES = ES)

ids = which(GSEA_GN3[[smpl]][[gene]]$all$indicator == 1)
ES = abs(GSEA_GN3[[smpl]][[gene]]$all$RES[ids])
data_GN3 <- data.frame(x = ids, ES = ES)

ids = which(GSEA_PIDC[[smpl]][[gene]]$all$indicator == 1)
ES = abs(GSEA_PIDC[[smpl]][[gene]]$all$RES[ids])
data_PIDC <- data.frame(x = ids, ES = ES)
```


```{r, fig.width=10, fig.height=5}
colors <- c("positive" = "red", "negative" = "navy")

xend = max(df$pos)
x1 = min(df$pos)
x2 = min(df$pos)
y1 = min(df[,c(2,3)]) - 0.05*(max(df[,c(2,3)])-min(df[,c(2,3)]))
y2 = max(df[,c(2,3)]) + 0.05*(max(df[,c(2,3)])-min(df[,c(2,3)]))

y_pos = max(df$scMINER_pos)
x_pos = which(df$scMINER_pos == max(df$scMINER_pos))

y_neg = min(df$scMINER_neg)
x_neg = which(df$scMINER_neg == min(df$scMINER_neg))

p1 <- ggplot(df, aes(x = pos)) + 
  geom_segment(aes(x = 0, xend = xend, y=0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = x1, xend = x2, y = y1, yend = y2), size = 0.5, color = "black") +
  geom_segment(aes(x = 0, xend = x_pos, y = y_pos, yend = y_pos), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_pos, xend = x_pos, y = 0, yend = y_pos), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_neg, y = y_neg, yend = y_neg), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_neg, xend = x_neg, y = 0, yend = y_neg), size = 0.2, color = "black", linetype = 5) +
  geom_line(aes(y=scMINER_pos, color = "positive"), size = 2) + 
  geom_line(aes(y=scMINER_neg, color = "negative"), size = 2) + 
  geom_point(x = x_pos, y = y_pos, colour = "black", size = 2) + 
  geom_point(x = x_neg, y = y_neg, colour = "black", size = 2) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = 0, color = "black", size = 6) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = y_pos, hjust = 1, label = round(y_pos,2), color = "black", size = 6) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = y_neg, hjust = 1, label = round(y_neg,2), color = "black", size = 6) + 
  ylab("Enrichment score") + xlab("") +
  theme_void(base_size = 16) +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), 
      axis.ticks.x=element_blank(), legend.position = "top",
      axis.title.y=element_text(angle = 90, size = 25),
      plot.title = element_text(size = 25)) +
  scale_color_manual(values = colors) + labs(color = "scMINER") + 
  scale_x_continuous(expand = expansion(mult = 0.1)) + 
  ggtitle(paste0("        ", gene, " activation, scMINER")) + theme(legend.position = "none")
p2 <- ggplot() + 
  geom_segment(data = data_pos, aes(x = x, xend = x, y = 0, yend = 1, alpha = abs(ES)), size = 0.3, color = "red") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 1, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = 0, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = dim(df)[1], xend = dim(df)[1], y = 0, yend = 1), size = 0.5, color = "black") +
  theme_void() + theme(legend.position = "none") + xlim(1, dim(df)[1]) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = " ", color = "black", size = 6) + 
  scale_x_continuous(expand = expansion(mult = 0.1))
p3 <- ggplot() + 
  geom_segment(data = data_neg, aes(x = x, xend = x, y = 0, yend = 1, alpha = abs(ES)), size = 0.3, color = "navy") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 1, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = 0, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = dim(df)[1], xend = dim(df)[1], y = 0, yend = 1), size = 0.5, color = "black") +
  theme_void() + theme(legend.position = "none") + xlim(1, dim(df)[1]) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = " ", color = "black", size = 6) + 
  scale_x_continuous(expand = expansion(mult = 0.1))

p <- plot_grid(p1, p2, p3, align = 'v', ncol = 1, rel_heights = c(1, 0.05, 0.05))


p <- p + annotate("text", x = 0.11, y = 0.025 + 0.045, hjust = 1, label = "Positive", color = "black", size = 5)
p <- p + annotate("text", x = 0.11, y = 0.025, hjust = 1, label = "Negative", color = "black", size = 5)


ES_pos = as.character(round(GSEA_scMINER[[smpl]][[gene]]$pos$ES, 3))
pv_pos = formatC(GSEA_scMINER[[smpl]][[gene]]$pos$ks_pv, format = "e", digits = 2)

ES_neg = as.character(round(GSEA_scMINER[[smpl]][[gene]]$neg$ES, 3))
pv_neg = formatC(GSEA_scMINER[[smpl]][[gene]]$neg$ks_pv, format = "e", digits = 2)

x_t = 0.6
x_delta1 = 0.11
x_delta2 = 0.08
y_t = 0.85
y_delta = 0.05

p <- p + annotate("text", x = x_t, y = y_t, hjust = 0, label = "Regulation", color = "black", size = 5)
p <- p + annotate("text", x = x_t, y = y_t - y_delta, hjust = 0, label = "Positive", color = "red", size = 5)
p <- p + annotate("text", x = x_t, y = y_t - 2*y_delta, hjust = 0, label = "Negative", color = "navy", size = 5)

p <- p + annotate("text", x = x_t + x_delta1, y = y_t, hjust = 0, label = "ES", color = "black", size = 5)
p <- p + annotate("text", x = x_t + x_delta1, y = y_t - y_delta, hjust = 0, label = ES_pos, color = "red", size = 5)
p <- p + annotate("text", x = x_t + x_delta1, y = y_t - 2*y_delta, hjust = 0, label = ES_neg, color = "navy", size = 5)

p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t, hjust = 0, label = "P-value", color = "black", size = 5)
p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t - y_delta, hjust = 0, label = pv_pos, color = "red", size = 5)
p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t - 2*y_delta, hjust = 0, label = pv_neg, color = "navy", size = 5)

p
```



```{r}
save_file = file.path(save_fold, paste0("TF_GSEA_", gene, "_activation_scMINER.png"))
png(save_file, height=5, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("TF_GSEA_", gene, "_activation_scMINER.pdf"))
pdf(save_file, height=5, width=10)
print(p)
dev.off()
```



```{r, fig.width=10, fig.height=5}
colors <- c("GRNBoost2" = "blue", "GENIE3" = "green", "PIDC" = "sandybrown")

xend = max(df$pos)
x1 = min(df$pos)
x2 = min(df$pos)
y1_true = min(df[,c(4,5,6)])
y2_true = max(df[,c(4,5,6)])
y1 = min(df[,c(4,5,6)]) - 0.05*(max(df[,c(4,5,6)])-min(df[,c(4,5,6)]))
y2 = max(df[,c(4,5,6)]) + 0.05*(max(df[,c(4,5,6)])-min(df[,c(4,5,6)]))

x_grnb_min = which(df$GRNBoost2 == min(df$GRNBoost2))
y_grnb_min = min(df$GRNBoost2)

x_grnb_max = which(df$GRNBoost2 == max(df$GRNBoost2))
y_grnb_max = max(df$GRNBoost2)


x_gn3_min = which(df$GENIE3 == min(df$GENIE3))
y_gn3_min = min(df$GENIE3)

x_gn3_max = which(df$GENIE3 == max(df$GENIE3))
y_gn3_max = max(df$GENIE3)


x_pidc_min = which(df$PIDC == min(df$PIDC))
y_pidc_min = min(df$PIDC)

x_pidc_max = which(df$PIDC == max(df$PIDC))
y_pidc_max = max(df$PIDC)

p1 <- ggplot(df, aes(x = pos)) + 
  geom_segment(aes(x = 0, xend = xend, y=0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = x1, xend = x2, y = y1, yend = y2), size = 0.5, color = "black") +
  geom_segment(aes(x = 0, xend = x_grnb_min, y = y_grnb_min, yend = y_grnb_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_grnb_min, xend = x_grnb_min, y = 0, yend = y_grnb_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_grnb_max, y = y_grnb_max, yend = y_grnb_max), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_grnb_max, xend = x_grnb_max, y = 0, yend = y_grnb_max), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_gn3_min, y = y_gn3_min, yend = y_gn3_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_gn3_min, xend = x_gn3_min, y = 0, yend = y_gn3_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_gn3_max, y = y_gn3_max, yend = y_gn3_max), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_gn3_max, xend = x_gn3_max, y = 0, yend = y_gn3_max), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_pidc_min, y = y_pidc_min, yend = y_pidc_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_pidc_min, xend = x_pidc_min, y = 0, yend = y_pidc_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_pidc_max, y = y_pidc_max, yend = y_pidc_max), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_pidc_max, xend = x_pidc_max, y = 0, yend = y_pidc_max), size = 0.2, color = "black", linetype = 5) +
  geom_line(aes(y=GRNBoost2, color = "GRNBoost2"), size = 2) + 
  geom_line(aes(y=GENIE3, color = "GENIE3"), size = 2) + 
  geom_line(aes(y=PIDC, color = "PIDC"), size = 2) + 
  geom_point(x = x_grnb_min, y = y_grnb_min, colour = "black", size = 2) + 
  geom_point(x = x_grnb_max, y = y_grnb_max, colour = "black", size = 2) + 
  geom_point(x = x_gn3_min, y = y_gn3_min, colour = "black", size = 2) + 
  geom_point(x = x_gn3_max, y = y_gn3_max, colour = "black", size = 2) + 
  geom_point(x = x_pidc_min, y = y_pidc_min, colour = "black", size = 2) + 
  geom_point(x = x_pidc_max, y = y_pidc_max, colour = "black", size = 2) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = 0, color = "black", size = 6) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = y1_true, hjust = 1, label = round(y1_true,2), color = "black", size = 6) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = y2_true, hjust = 1, label = round(y2_true,2), color = "black", size = 6) + 
  ylab("Enrichment score") + xlab("") +
  theme_void(base_size = 16) +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), 
      axis.ticks.x=element_blank(), legend.position = "top",
      axis.title.y=element_text(angle = 90, size = 25),
      plot.title = element_text(size = 25)) +
  labs(color = "Mothod") + scale_color_manual(values = colors) + 
  scale_x_continuous(expand = expansion(mult = 0.1)) + 
  ggtitle(paste0("        ", gene, " activation, alternative methods")) + theme(legend.position = "none")
p2 <- ggplot() + 
  geom_segment(data = data_GRNB2, aes(x = x, xend = x, y = 0, yend = 1, alpha = abs(ES)), size = 0.3, color = "blue") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 1, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = 0, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = dim(df)[1], xend = dim(df)[1], y = 0, yend = 1), size = 0.5, color = "black") +
  theme_void() + theme(legend.position = "none") + xlim(1, dim(df)[1]) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = " ", color = "black", size = 6) + 
  scale_x_continuous(expand = expansion(mult = 0.1))
p3 <- ggplot() + 
  geom_segment(data = data_GN3, aes(x = x, xend = x, y = 0, yend = 1, alpha = abs(ES)), size = 0.3, color = "green") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 1, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = 0, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = dim(df)[1], xend = dim(df)[1], y = 0, yend = 1), size = 0.5, color = "black") +
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = " ", color = "black", size = 6) + 
  theme_void() + theme(legend.position = "none") + xlim(1, dim(df)[1]) + 
  scale_x_continuous(expand = expansion(mult = 0.1))
p4 <- ggplot() + 
  geom_segment(data = data_PIDC, aes(x = x, xend = x, y = 0, yend = 1, alpha = abs(ES)), size = 0.3, color = "sandybrown") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 1, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = 0, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = dim(df)[1], xend = dim(df)[1], y = 0, yend = 1), size = 0.5, color = "black") +
  theme_void() + theme(legend.position = "none") + xlim(1, dim(df)[1]) +
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = " ", color = "black", size = 6) + 
  scale_x_continuous(expand = expansion(mult = 0.1))

p <- plot_grid(p1, p2, p3, p4, align = 'v', ncol = 1, rel_heights = c(1, 0.05, 0.05, 0.05))


p <- p + annotate("text", x = 0.11, y = 0.021 + 0.045*2, hjust = 1, label = "GRNBoost2", color = "black", size = 5)
p <- p + annotate("text", x = 0.11, y = 0.021 + 0.045, hjust = 1, label = "GENIE3", color = "black", size = 5)
p <- p + annotate("text", x = 0.11, y = 0.021, hjust = 1, label = "PIDC", color = "black", size = 5)


ES_grnb = as.character(round(GSEA_GRNB2[[smpl]][[gene]]$all$ES, 3))
pv_grnb = formatC(GSEA_GRNB2[[smpl]][[gene]]$all$ks_pv, format = "e", digits = 2)

ES_gn3 = as.character(round(GSEA_GN3[[smpl]][[gene]]$all$ES, 3))
pv_gn3 = formatC(GSEA_GN3[[smpl]][[gene]]$all$ks_pv, format = "e", digits = 2)

ES_pidc = as.character(round(GSEA_PIDC[[smpl]][[gene]]$all$ES, 3))
pv_pidc = formatC(GSEA_PIDC[[smpl]][[gene]]$all$ks_pv, format = "e", digits = 2)

x_t = 0.6
x_delta1 = 0.12
x_delta2 = 0.08
y_t = 0.85
y_delta = 0.05

p <- p + annotate("text", x = x_t, y = y_t, hjust = 0, label = "Method", color = "black", size = 5)
p <- p + annotate("text", x = x_t, y = y_t - y_delta, hjust = 0, label = "GRNBoost2", color = "blue", size = 5)
p <- p + annotate("text", x = x_t, y = y_t - 2*y_delta, hjust = 0, label = "GENIE3", color = "green", size = 5)
p <- p + annotate("text", x = x_t, y = y_t - 3*y_delta, hjust = 0, label = "PIDC", color = "sandybrown", size = 5)

p <- p + annotate("text", x = x_t + x_delta1, y = y_t, hjust = 0, label = "ES", color = "black", size = 5)
p <- p + annotate("text", x = x_t + x_delta1, y = y_t - y_delta, hjust = 0, label = ES_grnb, color = "blue", size = 5)
p <- p + annotate("text", x = x_t + x_delta1, y = y_t - 2*y_delta, hjust = 0, label = ES_gn3, color = "green", size = 5)
p <- p + annotate("text", x = x_t + x_delta1, y = y_t - 3*y_delta, hjust = 0, label = ES_pidc, color = "sandybrown", size = 5)


p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t, hjust = 0, label = "P-value", color = "black", size = 5)
p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t - y_delta, hjust = 0, label = pv_grnb, color = "blue", size = 5)
p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t - 2*y_delta, hjust = 0, label = pv_gn3, color = "green", size = 5)
p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t - 3*y_delta, hjust = 0, label = pv_pidc, color = "sandybrown", size = 5)


p
```



```{r}
save_file = file.path(save_fold, paste0("TF_GSEA_", gene, "_activation_alternative_methods.png"))
png(save_file, height=5, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("TF_GSEA_", gene, "_activation_alternative_methods.pdf"))
pdf(save_file, height=5, width=10)
print(p)
dev.off()
```








```{r}
options(scipen = 0)
options(digits = 2)

smpl = "D1_i"
gene = "BATF3"
rank_profile = GSEA_scMINER[[smpl]][[gene]]$pos$r_p
df <- data.frame(rank_profile = GSEA_scMINER[[smpl]][[gene]]$pos$r_p,
                 scMINER_pos = GSEA_scMINER[[smpl]][[gene]]$pos$RES,
                 scMINER_neg = GSEA_scMINER[[smpl]][[gene]]$neg$RES,
                 GRNBoost2 = GSEA_GRNB2[[smpl]][[gene]]$all$RES,
                 GENIE3 = GSEA_GN3[[smpl]][[gene]]$all$RES,
                 PIDC = GSEA_PIDC[[smpl]][[gene]]$all$RES, 
                 pos = 1:length(GSEA_scMINER[[smpl]][[gene]]$pos$r_p))

ids_pos = which(GSEA_scMINER[[smpl]][[gene]]$pos$indicator == 1)
ES_pos = abs(GSEA_scMINER[[smpl]][[gene]]$pos$RES[ids_pos])
data_pos <- data.frame(x = ids_pos, ES = ES_pos)

ids_neg = which(GSEA_scMINER[[smpl]][[gene]]$neg$indicator == 1)
ES_neg = abs(GSEA_scMINER[[smpl]][[gene]]$neg$RES[ids_neg])
data_neg <- data.frame(x = ids_neg, ES = ES_neg)

ids = which(GSEA_GRNB2[[smpl]][[gene]]$all$indicator == 1)
ES = abs(GSEA_GRNB2[[smpl]][[gene]]$all$RES[ids])
data_GRNB2 <- data.frame(x = ids, ES = ES)

ids = which(GSEA_GN3[[smpl]][[gene]]$all$indicator == 1)
ES = abs(GSEA_GN3[[smpl]][[gene]]$all$RES[ids])
data_GN3 <- data.frame(x = ids, ES = ES)

ids = which(GSEA_PIDC[[smpl]][[gene]]$all$indicator == 1)
ES = abs(GSEA_PIDC[[smpl]][[gene]]$all$RES[ids])
data_PIDC <- data.frame(x = ids, ES = ES)
```





```{r, fig.width=10, fig.height=5}
colors <- c("positive" = "red", "negative" = "navy")

xend = max(df$pos)
x1 = min(df$pos)
x2 = min(df$pos)
y1 = min(df[,c(2,3)]) - 0.05*(max(df[,c(2,3)])-min(df[,c(2,3)]))
y2 = max(df[,c(2,3)]) + 0.05*(max(df[,c(2,3)])-min(df[,c(2,3)]))

y_pos = min(df$scMINER_pos)
x_pos = which(df$scMINER_pos == min(df$scMINER_pos))

y_neg = max(df$scMINER_neg)
x_neg = which(df$scMINER_neg == max(df$scMINER_neg))

p1 <- ggplot(df, aes(x = pos)) + 
  geom_segment(aes(x = 0, xend = xend, y=0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = x1, xend = x2, y = y1, yend = y2), size = 0.5, color = "black") +
  geom_segment(aes(x = 0, xend = x_pos, y = y_pos, yend = y_pos), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_pos, xend = x_pos, y = 0, yend = y_pos), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_neg, y = y_neg, yend = y_neg), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_neg, xend = x_neg, y = 0, yend = y_neg), size = 0.2, color = "black", linetype = 5) +
  geom_line(aes(y=scMINER_pos, color = "positive"), size = 2) + 
  geom_line(aes(y=scMINER_neg, color = "negative"), size = 2) + 
  geom_point(x = x_pos, y = y_pos, colour = "black", size = 2) + 
  geom_point(x = x_neg, y = y_neg, colour = "black", size = 2) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = 0, color = "black", size = 6) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = y_pos, hjust = 1, label = round(y_pos,2), color = "black", size = 6) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = y_neg, hjust = 1, label = round(y_neg,2), color = "black", size = 6) + 
  ylab("Enrichment score") + xlab("") +
  theme_void(base_size = 16) +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), 
      axis.ticks.x=element_blank(), legend.position = "top",
      axis.title.y=element_text(angle = 90, size = 25),
      plot.title = element_text(size = 25)) +
  scale_color_manual(values = colors) + labs(color = "scMINER") + 
  scale_x_continuous(expand = expansion(mult = 0.1)) + 
  ggtitle(paste0("        ", gene, " interference, scMINER")) + theme(legend.position = "none")
p2 <- ggplot() + 
  geom_segment(data = data_pos, aes(x = x, xend = x, y = 0, yend = 1, alpha = abs(ES)), size = 0.3, color = "red") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 1, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = 0, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = dim(df)[1], xend = dim(df)[1], y = 0, yend = 1), size = 0.5, color = "black") +
  theme_void() + theme(legend.position = "none") + xlim(1, dim(df)[1]) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = " ", color = "black", size = 6) + 
  scale_x_continuous(expand = expansion(mult = 0.1))
p3 <- ggplot() + 
  geom_segment(data = data_neg, aes(x = x, xend = x, y = 0, yend = 1, alpha = abs(ES)), size = 0.3, color = "navy") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 1, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = 0, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = dim(df)[1], xend = dim(df)[1], y = 0, yend = 1), size = 0.5, color = "black") +
  theme_void() + theme(legend.position = "none") + xlim(1, dim(df)[1]) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = " ", color = "black", size = 6) + 
  scale_x_continuous(expand = expansion(mult = 0.1))

p <- plot_grid(p1, p2, p3, align = 'v', ncol = 1, rel_heights = c(1, 0.05, 0.05))


p <- p + annotate("text", x = 0.11, y = 0.025 + 0.045, hjust = 1, label = "Positive", color = "black", size = 5)
p <- p + annotate("text", x = 0.11, y = 0.025, hjust = 1, label = "Negative", color = "black", size = 5)


ES_pos = as.character(round(GSEA_scMINER[[smpl]][[gene]]$pos$ES, 3))
pv_pos = formatC(GSEA_scMINER[[smpl]][[gene]]$pos$ks_pv, format = "e", digits = 2)

ES_neg = as.character(round(GSEA_scMINER[[smpl]][[gene]]$neg$ES, 3))
pv_neg = formatC(GSEA_scMINER[[smpl]][[gene]]$neg$ks_pv, format = "e", digits = 2)

x_t = 0.6
x_delta1 = 0.11
x_delta2 = 0.08
y_t = 0.85
y_delta = 0.05

p <- p + annotate("text", x = x_t, y = y_t, hjust = 0, label = "Regulation", color = "black", size = 5)
p <- p + annotate("text", x = x_t, y = y_t - y_delta, hjust = 0, label = "Positive", color = "red", size = 5)
p <- p + annotate("text", x = x_t, y = y_t - 2*y_delta, hjust = 0, label = "Negative", color = "navy", size = 5)

p <- p + annotate("text", x = x_t + x_delta1, y = y_t, hjust = 0, label = "ES", color = "black", size = 5)
p <- p + annotate("text", x = x_t + x_delta1, y = y_t - y_delta, hjust = 0, label = ES_pos, color = "red", size = 5)
p <- p + annotate("text", x = x_t + x_delta1, y = y_t - 2*y_delta, hjust = 0, label = ES_neg, color = "navy", size = 5)

p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t, hjust = 0, label = "P-value", color = "black", size = 5)
p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t - y_delta, hjust = 0, label = pv_pos, color = "red", size = 5)
p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t - 2*y_delta, hjust = 0, label = pv_neg, color = "navy", size = 5)

p
```



```{r}
save_file = file.path(save_fold, paste0("TF_GSEA_", gene, "_interference_scMINER.png"))
png(save_file, height=5, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("TF_GSEA_", gene, "_interference_scMINER.pdf"))
pdf(save_file, height=5, width=10)
print(p)
dev.off()
```



```{r, fig.width=10, fig.height=5}
colors <- c("GRNBoost2" = "blue", "GENIE3" = "green", "PIDC" = "sandybrown")

xend = max(df$pos)
x1 = min(df$pos)
x2 = min(df$pos)
y1_true = min(df[,c(4,5,6)])
y2_true = max(df[,c(4,5,6)])
y1 = min(df[,c(4,5,6)]) - 0.05*(max(df[,c(4,5,6)])-min(df[,c(4,5,6)]))
y2 = max(df[,c(4,5,6)]) + 0.05*(max(df[,c(4,5,6)])-min(df[,c(4,5,6)]))

x_grnb_min = which(df$GRNBoost2 == min(df$GRNBoost2))
y_grnb_min = min(df$GRNBoost2)

x_grnb_max = which(df$GRNBoost2 == max(df$GRNBoost2))
y_grnb_max = max(df$GRNBoost2)


x_gn3_min = which(df$GENIE3 == min(df$GENIE3))
y_gn3_min = min(df$GENIE3)

x_gn3_max = which(df$GENIE3 == max(df$GENIE3))
y_gn3_max = max(df$GENIE3)


x_pidc_min = which(df$PIDC == min(df$PIDC))
y_pidc_min = min(df$PIDC)

x_pidc_max = which(df$PIDC == max(df$PIDC))
y_pidc_max = max(df$PIDC)

p1 <- ggplot(df, aes(x = pos)) + 
  geom_segment(aes(x = 0, xend = xend, y=0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = x1, xend = x2, y = y1, yend = y2), size = 0.5, color = "black") +
  geom_segment(aes(x = 0, xend = x_grnb_min, y = y_grnb_min, yend = y_grnb_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_grnb_min, xend = x_grnb_min, y = 0, yend = y_grnb_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_grnb_max, y = y_grnb_max, yend = y_grnb_max), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_grnb_max, xend = x_grnb_max, y = 0, yend = y_grnb_max), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_gn3_min, y = y_gn3_min, yend = y_gn3_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_gn3_min, xend = x_gn3_min, y = 0, yend = y_gn3_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_gn3_max, y = y_gn3_max, yend = y_gn3_max), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_gn3_max, xend = x_gn3_max, y = 0, yend = y_gn3_max), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_pidc_min, y = y_pidc_min, yend = y_pidc_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_pidc_min, xend = x_pidc_min, y = 0, yend = y_pidc_min), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = 0, xend = x_pidc_max, y = y_pidc_max, yend = y_pidc_max), size = 0.2, color = "black", linetype = 5) +
  geom_segment(aes(x = x_pidc_max, xend = x_pidc_max, y = 0, yend = y_pidc_max), size = 0.2, color = "black", linetype = 5) +
  geom_line(aes(y=GRNBoost2, color = "GRNBoost2"), size = 2) + 
  geom_line(aes(y=GENIE3, color = "GENIE3"), size = 2) + 
  geom_line(aes(y=PIDC, color = "PIDC"), size = 2) + 
  geom_point(x = x_grnb_min, y = y_grnb_min, colour = "black", size = 2) + 
  geom_point(x = x_grnb_max, y = y_grnb_max, colour = "black", size = 2) + 
  geom_point(x = x_gn3_min, y = y_gn3_min, colour = "black", size = 2) + 
  geom_point(x = x_gn3_max, y = y_gn3_max, colour = "black", size = 2) + 
  geom_point(x = x_pidc_min, y = y_pidc_min, colour = "black", size = 2) + 
  geom_point(x = x_pidc_max, y = y_pidc_max, colour = "black", size = 2) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = 0, color = "black", size = 6) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = y1_true, hjust = 1, label = round(y1_true,2), color = "black", size = 6) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = y2_true, hjust = 1, label = round(y2_true,2), color = "black", size = 6) + 
  ylab("Enrichment score") + xlab("") +
  theme_void(base_size = 16) +
  theme(axis.title.x=element_blank(), axis.text.x=element_blank(), 
      axis.ticks.x=element_blank(), legend.position = "top",
      axis.title.y=element_text(angle = 90, size = 25),
      plot.title = element_text(size = 25)) +
  labs(color = "Mothod") + scale_color_manual(values = colors) + 
  scale_x_continuous(expand = expansion(mult = 0.1)) + 
  ggtitle(paste0("         ", gene, " interference, alternative methods")) + theme(legend.position = "none")
p2 <- ggplot() + 
  geom_segment(data = data_GRNB2, aes(x = x, xend = x, y = 0, yend = 1, alpha = abs(ES)), size = 0.3, color = "blue") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 1, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = 0, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = dim(df)[1], xend = dim(df)[1], y = 0, yend = 1), size = 0.5, color = "black") +
  theme_void() + theme(legend.position = "none") + xlim(1, dim(df)[1]) + 
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = " ", color = "black", size = 6) + 
  scale_x_continuous(expand = expansion(mult = 0.1))
p3 <- ggplot() + 
  geom_segment(data = data_GN3, aes(x = x, xend = x, y = 0, yend = 1, alpha = abs(ES)), size = 0.3, color = "green") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 1, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = 0, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = dim(df)[1], xend = dim(df)[1], y = 0, yend = 1), size = 0.5, color = "black") +
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = " ", color = "black", size = 6) + 
  theme_void() + theme(legend.position = "none") + xlim(1, dim(df)[1]) + 
  scale_x_continuous(expand = expansion(mult = 0.1))
p4 <- ggplot() + 
  geom_segment(data = data_PIDC, aes(x = x, xend = x, y = 0, yend = 1, alpha = abs(ES)), size = 0.3, color = "sandybrown") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 1, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = dim(df)[1], y = 0, yend = 0), size = 0.5, color = "black") +
  geom_segment(aes(x = 1, xend = 1, y = 0, yend = 1), size = 0.5, color = "black") +
  geom_segment(aes(x = dim(df)[1], xend = dim(df)[1], y = 0, yend = 1), size = 0.5, color = "black") +
  theme_void() + theme(legend.position = "none") + xlim(1, dim(df)[1]) +
  annotate(geom = "text", x = 0 - 0.005*xend, y = 0, hjust = 1, label = " ", color = "black", size = 6) + 
  scale_x_continuous(expand = expansion(mult = 0.1))

p <- plot_grid(p1, p2, p3, p4, align = 'v', ncol = 1, rel_heights = c(1, 0.05, 0.05, 0.05))


p <- p + annotate("text", x = 0.11, y = 0.021 + 0.045*2, hjust = 1, label = "GRNBoost2", color = "black", size = 5)
p <- p + annotate("text", x = 0.11, y = 0.021 + 0.045, hjust = 1, label = "GENIE3", color = "black", size = 5)
p <- p + annotate("text", x = 0.11, y = 0.021, hjust = 1, label = "PIDC", color = "black", size = 5)


ES_grnb = as.character(round(GSEA_GRNB2[[smpl]][[gene]]$all$ES, 3))
pv_grnb = formatC(GSEA_GRNB2[[smpl]][[gene]]$all$ks_pv, format = "e", digits = 2)

ES_gn3 = as.character(round(GSEA_GN3[[smpl]][[gene]]$all$ES, 3))
pv_gn3 = formatC(GSEA_GN3[[smpl]][[gene]]$all$ks_pv, format = "e", digits = 2)

ES_pidc = as.character(round(GSEA_PIDC[[smpl]][[gene]]$all$ES, 3))
pv_pidc = formatC(GSEA_PIDC[[smpl]][[gene]]$all$ks_pv, format = "e", digits = 2)

x_t = 0.15
x_delta1 = 0.12
x_delta2 = 0.08
y_t = 0.5
y_delta = 0.05

p <- p + annotate("text", x = x_t, y = y_t, hjust = 0, label = "Method", color = "black", size = 5)
p <- p + annotate("text", x = x_t, y = y_t - y_delta, hjust = 0, label = "GRNBoost2", color = "blue", size = 5)
p <- p + annotate("text", x = x_t, y = y_t - 2*y_delta, hjust = 0, label = "GENIE3", color = "green", size = 5)
p <- p + annotate("text", x = x_t, y = y_t - 3*y_delta, hjust = 0, label = "PIDC", color = "sandybrown", size = 5)

p <- p + annotate("text", x = x_t + x_delta1, y = y_t, hjust = 0, label = "ES", color = "black", size = 5)
p <- p + annotate("text", x = x_t + x_delta1, y = y_t - y_delta, hjust = 0, label = ES_grnb, color = "blue", size = 5)
p <- p + annotate("text", x = x_t + x_delta1, y = y_t - 2*y_delta, hjust = 0, label = ES_gn3, color = "green", size = 5)
p <- p + annotate("text", x = x_t + x_delta1, y = y_t - 3*y_delta, hjust = 0, label = ES_pidc, color = "sandybrown", size = 5)


p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t, hjust = 0, label = "P-value", color = "black", size = 5)
p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t - y_delta, hjust = 0, label = pv_grnb, color = "blue", size = 5)
p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t - 2*y_delta, hjust = 0, label = pv_gn3, color = "green", size = 5)
p <- p + annotate("text", x = x_t + x_delta1 + x_delta2, y = y_t - 3*y_delta, hjust = 0, label = pv_pidc, color = "sandybrown", size = 5)


p
```



```{r}
save_file = file.path(save_fold, paste0("TF_GSEA_", gene, "_interference_alternative_methods.png"))
png(save_file, height=5, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("TF_GSEA_", gene, "_interference_alternative_methods.pdf"))
pdf(save_file, height=5, width=10)
print(p)
dev.off()
```



```{r}
D1_a_targets <- sel_tar_per_sample[["D1_a"]]
D1_i_targets <- sel_tar_per_sample[["D1_i"]]
D2_a_targets <- sel_tar_per_sample[["D2_a"]]
D2_i_targets <- sel_tar_per_sample[["D2_i"]]
D3_a_targets <- sel_tar_per_sample[["D3_a"]]
D3_i_targets <- sel_tar_per_sample[["D3_i"]]
```


```{r}
D1_sel_targets = union(sel_tar_per_sample$D1_a, sel_tar_per_sample$D1_i)
D2_sel_targets = union(sel_tar_per_sample$D2_a, sel_tar_per_sample$D2_i)
D3_sel_targets = union(sel_tar_per_sample$D3_a, sel_tar_per_sample$D3_i)
sel_targets = Reduce(union, list(D1_sel_targets, D2_sel_targets, D3_sel_targets))
```

```{r}
smpl = "D1_a"
pv_scMINER_pos <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$pos$ks_pv)
pv_scMINER_neg <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$neg$ks_pv)
pv_scMINER_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$all$ks_pv)
pv_scMINER_all_fm <- sapply(sel_tar_per_sample[[smpl]], function(gene) 
  ifelse(is.null(GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv), NA, GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv))
pv_GRNB2_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GRNB2[[smpl]][[gene]]$all$ks_pv)
pv_GN3_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GN3[[smpl]][[gene]]$all$ks_pv)
pv_PIDC_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_PIDC[[smpl]][[gene]]$all$ks_pv)
D1_a_ks <- as.data.frame(Reduce(cbind, list(pv_scMINER_pos, pv_scMINER_neg, pv_scMINER_all, pv_scMINER_all_fm, pv_GRNB2_all, pv_GN3_all, pv_PIDC_all)))
colnames(D1_a_ks) <- c("scMINER_pos", "scMINER_neg", "scMINER_all", "scMINER_all_FM",  "GRNBoost2", "GENIE3", "PIDC")
D1_a_ks <- -log(D1_a_ks, base = 10)

smpl = "D1_i"
pv_scMINER_pos <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$pos$ks_pv)
pv_scMINER_neg <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$neg$ks_pv)
pv_scMINER_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$all$ks_pv)
pv_scMINER_all_fm <- sapply(sel_tar_per_sample[[smpl]], function(gene) 
  ifelse(is.null(GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv), NA, GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv))
pv_GRNB2_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GRNB2[[smpl]][[gene]]$all$ks_pv)
pv_GN3_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GN3[[smpl]][[gene]]$all$ks_pv)
pv_PIDC_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_PIDC[[smpl]][[gene]]$all$ks_pv)
D1_i_ks <- as.data.frame(Reduce(cbind, list(pv_scMINER_pos, pv_scMINER_neg, pv_scMINER_all, pv_scMINER_all_fm, pv_GRNB2_all, pv_GN3_all, pv_PIDC_all)))
colnames(D1_i_ks) <- c("scMINER_pos", "scMINER_neg", "scMINER_all", "scMINER_all_FM",  "GRNBoost2", "GENIE3", "PIDC")
D1_i_ks <- -log(D1_i_ks, base = 10)

smpl = "D2_a"
pv_scMINER_pos <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$pos$ks_pv)
pv_scMINER_neg <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$neg$ks_pv)
pv_scMINER_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$all$ks_pv)
pv_scMINER_all_fm <- sapply(sel_tar_per_sample[[smpl]], function(gene) 
  ifelse(is.null(GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv), NA, GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv))
pv_GRNB2_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GRNB2[[smpl]][[gene]]$all$ks_pv)
pv_GN3_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GN3[[smpl]][[gene]]$all$ks_pv)
pv_PIDC_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_PIDC[[smpl]][[gene]]$all$ks_pv)
D2_a_ks <- as.data.frame(Reduce(cbind, list(pv_scMINER_pos, pv_scMINER_neg, pv_scMINER_all, pv_scMINER_all_fm, pv_GRNB2_all, pv_GN3_all, pv_PIDC_all)))
colnames(D2_a_ks) <- c("scMINER_pos", "scMINER_neg", "scMINER_all", "scMINER_all_FM",  "GRNBoost2", "GENIE3", "PIDC")
D2_a_ks <- -log(D2_a_ks, base = 10)

smpl = "D2_i"
pv_scMINER_pos <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$pos$ks_pv)
pv_scMINER_neg <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$neg$ks_pv)
pv_scMINER_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$all$ks_pv)
pv_scMINER_all_fm <- sapply(sel_tar_per_sample[[smpl]], function(gene) 
  ifelse(is.null(GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv), NA, GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv))
pv_GRNB2_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GRNB2[[smpl]][[gene]]$all$ks_pv)
pv_GN3_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GN3[[smpl]][[gene]]$all$ks_pv)
pv_PIDC_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_PIDC[[smpl]][[gene]]$all$ks_pv)
D2_i_ks <- as.data.frame(Reduce(cbind, list(pv_scMINER_pos, pv_scMINER_neg, pv_scMINER_all, pv_scMINER_all_fm, pv_GRNB2_all, pv_GN3_all, pv_PIDC_all)))
colnames(D2_i_ks) <- c("scMINER_pos", "scMINER_neg", "scMINER_all", "scMINER_all_FM",  "GRNBoost2", "GENIE3", "PIDC")
D2_i_ks <- -log(D2_i_ks, base = 10)

smpl = "D3_a"
pv_scMINER_pos <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$pos$ks_pv)
pv_scMINER_neg <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$neg$ks_pv)
pv_scMINER_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$all$ks_pv)
pv_scMINER_all_fm <- sapply(sel_targets, function(gene) 
  ifelse(is.null(GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv), NA, GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv))
pv_GRNB2_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GRNB2[[smpl]][[gene]]$all$ks_pv)
pv_GN3_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GN3[[smpl]][[gene]]$all$ks_pv)
pv_PIDC_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_PIDC[[smpl]][[gene]]$all$ks_pv)
D3_a_ks <- as.data.frame(Reduce(cbind, list(pv_scMINER_pos, pv_scMINER_neg, pv_scMINER_all, pv_scMINER_all_fm, pv_GRNB2_all, pv_GN3_all, pv_PIDC_all)))
colnames(D3_a_ks) <- c("scMINER_pos", "scMINER_neg", "scMINER_all", "scMINER_all_FM",  "GRNBoost2", "GENIE3", "PIDC")
D3_a_ks <- -log(D3_a_ks, base = 10)

smpl = "D3_i"
pv_scMINER_pos <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$pos$ks_pv)
pv_scMINER_neg <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$neg$ks_pv)
pv_scMINER_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_scMINER[[smpl]][[gene]]$all$ks_pv)
pv_scMINER_all_fm <- sapply(sel_tar_per_sample[[smpl]], function(gene) 
  ifelse(is.null(GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv), NA, GSEA_scMINER[[smpl]][[gene]]$all$fisher_pv))
pv_GRNB2_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GRNB2[[smpl]][[gene]]$all$ks_pv)
pv_GN3_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_GN3[[smpl]][[gene]]$all$ks_pv)
pv_PIDC_all <- sapply(sel_tar_per_sample[[smpl]], function(gene) GSEA_PIDC[[smpl]][[gene]]$all$ks_pv)
D3_i_ks <- as.data.frame(Reduce(cbind, list(pv_scMINER_pos, pv_scMINER_neg, pv_scMINER_all, pv_scMINER_all_fm, pv_GRNB2_all, pv_GN3_all, pv_PIDC_all)))
colnames(D3_i_ks) <- c("scMINER_pos", "scMINER_neg", "scMINER_all", "scMINER_all_FM",  "GRNBoost2", "GENIE3", "PIDC")
D3_i_ks <- -log(D3_i_ks, base = 10)
```


```{r, fig.width=3.5, fig.height=3}
library(hrbrthemes)

gene_ord = c("NFATC3", "FLI1", "BATF", "JUN", "CREM", "BATF3")

df = data.frame(scMINER = D1_a_ks$scMINER_all_FM,
           GRNBoost2 = D1_a_ks$GRNBoost2,
           GENIE3 = D1_a_ks$GENIE3,
           PIDC = D1_a_ks$PIDC)
rownames(df) <- rownames(D1_a_ks)
df = df[rowSums(is.na(df)) == 0,]
all_pv = unlist(as.vector(df))
df$target <- rownames(df)
df <- melt(df, id = c("target"))
colnames(df) <- c("target", "method", "value")
df$target = factor(df$target, levels = gene_ord)
p <- ggplot(df, aes(x = method, y = target, fill = value)) +
  geom_tile() + scale_fill_gradient2(low="white", high="red") + 
  geom_text(aes(label = round(value,2)), color = "black", size = 4) +
  theme_classic() + 
  #ggtitle("GSEA KS P-value, activation") + 
  labs(fill="-lop(P-value)") + 
  ylab("") + xlab("") + 
  theme(legend.position = "none", axis.text.x=element_text(size=12)) +
  scale_x_discrete(guide = guide_axis(angle = 45))
p
```

```{r}
save_file = file.path(save_fold, "TF_GSEA_pv_activation.png")
png(save_file, height=3, width=3.5, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, "TF_GSEA_pv_activation.pdf")
pdf(save_file, height=3, width=3.5)
p
dev.off()
```



```{r, fig.width=3.5, fig.height=3}
library(hrbrthemes)

gene_ord = c("FLI1", "JUN", "NFATC3", "BATF", "CREM", "BATF3")

df = data.frame(scMINER = D1_i_ks$scMINER_all_FM,
           GRNBoost2 = D1_i_ks$GRNBoost2,
           GENIE3 = D1_i_ks$GENIE3,
           PIDC = D1_i_ks$PIDC)
rownames(df) <- rownames(D1_i_ks)
df = df[rowSums(is.na(df)) == 0,]
all_pv = unlist(as.vector(df))
df$target <- rownames(df)
df = df[-6,]
df <- melt(df, id = c("target"))
colnames(df) <- c("target", "method", "value")
df$target = factor(df$target, levels = gene_ord)
p <- ggplot(df, aes(x = method, y = target, fill = value)) +
  geom_tile() + scale_fill_gradient2(low="white", high="red") + 
  geom_text(aes(label = round(value,2)), color = "black", size = 4) +
  theme_classic() + 
  #ggtitle("GSEA KS P-value, interference") + 
  labs(fill="-lop(P-value)") + 
  ylab("") + xlab("") + 
  theme(legend.position = "none", axis.text.x=element_text(size=12)) +
  scale_x_discrete(guide = guide_axis(angle = 45))
p
```

```{r}
save_file = file.path(save_fold, "TF_GSEA_pv_interference.png")
png(save_file, height=3, width=3.5, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, "TF_GSEA_pv_interference.pdf")
pdf(save_file, height=3, width=3.5)
p
dev.off()
```



