---
title: "NES_TF_plot"
output: html_document
date: "2024-08-27"
---


```{r}
rm(list = ls())
```


```{r}
library(Seurat)
library(NetBID2)
library(ggplot2)
library(gridExtra)
library(cowplot)
library(grid)
library(dplyr)
library(scMINER)
library(patchwork)
library(gplots)
library(DropletUtils)
library(scater)
library(scran)
library(SingleCellExperiment)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(EnsDb.Hsapiens.v86)
library(EnsDb.Mmusculus.v79)
library(hrbrthemes)
library(ggpubr)
library(rstatix)
library(reshape)
library(RColorBrewer)
#display.brewer.all()
library(pals)
library(SingleR)
library(pheatmap)
library(igraph)
library(ggraph)
library(graphlayouts)
library(ggforce)
library(scDblFinder)
library(anndata)
library(reticulate)
```


```{r}
inp_file = "/Volumes/shladysh/scMINER/figures/CROP_Seq_GRN_evaluation/Yao_Regev_Cleary/data/NT_TF_GSEA_NES.Rdata"
load(inp_file)
```

```{r}
save_fold = "/Volumes/shladysh/scMINER/figures/CROP_Seq_GRN_evaluation/Yao_Regev_Cleary/results"
```

```{r}
NES <- as.data.frame(Reduce(cbind, list(NES_scMINER_pos, NES_scMINER_neg, NES_GN3, NES_GRNB2, NES_PIDC)))
colnames(NES) <- c("scMINER_pos", "scMINER_neg", "GENIE3", "GRNBoost2", "PIDC")
NES[!is.nan(rowSums(as.matrix(NES))),]
```


```{r, fig.width = 5, fig.height = 6}
options(scipen = 100, digits = 2)

data <- abs(NES)
data = data[rowSums(is.na(data)) == 0,]

df = as.data.frame(t(sapply(1:5, 
                            function(i) {x = data[,i]; 
                            w_test = wilcox.test(x, conf.level=0.95, conf.int=TRUE); 
                            outp = c(pos = i, estimate = w_test$estimate[[1]], CI1 = w_test$conf.int[1], CI2 = w_test$conf.int[2])
                            return(outp)})))
df$method = factor(x = c("scMINER_pos", "scMINER_neg", "GENIE3", "GRNBoost2", "PIDC"), levels = c("scMINER_pos", "scMINER_neg", "GENIE3", "GRNBoost2", "PIDC"))
bar_start = 1.05*max(df$CI2)
bar_inc = 0.05*bar_start
stat.test <- reshape::melt(data, variable_name = "method") %>% wilcox_test(value ~ method, paired = TRUE)
stat.test <- stat.test %>% add_xy_position(x = "method")
stat.test$y.position = bar_start + c(-1, 0, 1, 2, 4, 5, 6, 7, 8, 9)*bar_inc
stat.test <- stat.test[-c(1, 8, 9, 10), ]

p <- ggplot(df, aes(x=method, y=estimate)) +
  geom_bar(aes(fill=method), stat = "identity") +
  geom_errorbar(aes(ymin = CI1, ymax = CI2), width = 0.1) + 
  #theme_linedraw(base_size = 16) + 
  theme_classic(base_size = 16) + 
  stat_pvalue_manual(stat.test, label = "p.adj.signif", tip.length = 0.01) +
  scale_fill_manual(name = 'Method',
                    values = c("scMINER_pos" = "red", "scMINER_neg" = "navy", "GENIE3" = "green", "GRNBoost2" = "blue", "PIDC" = "sandybrown")) + 
  xlab("") + ylab("|NES|") + 
  ggtitle(paste0("GSEA, NES, ", "TF")) + theme(legend.position = "none") + 
  scale_x_discrete(guide = guide_axis(angle = 45),
                   labels = c("scMINER_pos" = "scMINER\npositive", 
                              "scMINER_neg" = "scMINER\nnegative", 
                              "GENIE3" = "GENIE3", 
                              "GRNBoost2" = "GRNBoost2", 
                              "PIDC" = "PIDC"))
p
```



```{r}
save_file = file.path(save_fold, paste0("TF_GSEA_abs_NES_barplot", ".png"))
png(save_file, height=6, width=5, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("TF_GSEA_abs_NES_barplot", ".pdf"))
pdf(save_file, height=6, width=5)
p
dev.off()
```




```{r, fig.width = 5, fig.height = 6}
options(scipen = 100, digits = 2)

data <- NES
data = data[rowSums(is.na(data)) == 0,]

df = as.data.frame(t(sapply(1:5, 
                            function(i) {x = data[,i]; 
                            w_test = wilcox.test(x, conf.level=0.95, conf.int=TRUE); 
                            outp = c(pos = i, estimate = w_test$estimate[[1]], CI1 = w_test$conf.int[1], CI2 = w_test$conf.int[2])
                            return(outp)})))
df$method = factor(x = c("scMINER_pos", "scMINER_neg", "GRNBoost2", "GENIE3", "PIDC"), levels = c("scMINER_pos", "scMINER_neg", "GENIE3", "GRNBoost2", "PIDC"))
bar_start = 1.05*max(df$CI2)
bar_inc = 0.05*bar_start
stat.test <- reshape::melt(data, variable_name = "method") %>% wilcox_test(value ~ method, paired = TRUE)
stat.test <- stat.test %>% add_xy_position(x = "method")
stat.test$y.position = bar_start + c(-1, 0, 1, 2, 4, 5, 6, 7, 8, 9)*bar_inc
stat.test <- stat.test[-c(1, 8, 9, 10), ]

p <- ggplot(df, aes(x=method, y=estimate)) +
  geom_bar(aes(fill=method), stat = "identity") +
  geom_errorbar(aes(ymin = CI1, ymax = CI2), width = 0.1) + 
  #theme_linedraw(base_size = 16) + 
  theme_classic(base_size = 16) + 
  scale_fill_manual(name = 'Method',
                    values = c("scMINER_pos" = "red", "scMINER_neg" = "navy", "GENIE3" = "green", "GRNBoost2" = "blue", "PIDC" = "sandybrown")) + 
  xlab("") + ylab("NES") + 
  ggtitle(paste0("GSEA, NES, ", "TF")) + theme(legend.position = "none") + 
  scale_x_discrete(guide = guide_axis(angle = 45))
p
```



```{r}
save_file = file.path(save_fold, paste0("TF_GSEA_NES_barplot", ".png"))
png(save_file, height=6, width=5, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("TF_GSEA_NES_barplot", ".pdf"))
pdf(save_file, height=6, width=5)
p
dev.off()
```

```{r, fig.width = 5, fig.height = 6}
df = melt(NES)
colnames(df) <- c("Method", "NES")
p <- ggplot(df, aes(x = Method, y = NES, fill = Method)) + 
  geom_violin() +
  theme_classic(base_size = 16) + 
  scale_fill_manual(name = 'Method',
                    values = c("scMINER_pos" = "red", "scMINER_neg" = "navy", "GENIE3" = "green", "GRNBoost2" = "blue", "PIDC" = "sandybrown")) + 
  xlab("") + ylab("NES") + 
  ggtitle(paste0("GSEA, NES, ", "TF")) + theme(legend.position = "none") + 
  scale_x_discrete(guide = guide_axis(angle = 45))
p
```

```{r}
save_file = file.path(save_fold, paste0("TF_GSEA_NES_violin", ".png"))
png(save_file, height=6, width=5, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("TF_GSEA_NES_violin", ".pdf"))
pdf(save_file, height=6, width=5)
p
dev.off()
```



```{r, fig.width = 5, fig.height = 6}
options(scipen = 100, digits = 2)

data <- abs(NES)
data = data[rowSums(is.na(data)) == 0,]

w_test = wilcox.test(c(data$scMINER_pos, data$scMINER_neg), conf.level=0.95, conf.int=TRUE)
outp1 = c(pos = 1, estimate = w_test$estimate[[1]], CI1 = w_test$conf.int[1], CI2 = w_test$conf.int[2])

w_test = wilcox.test(data$GENIE3, conf.level=0.95, conf.int=TRUE)
outp2 = c(pos = 2, estimate = w_test$estimate[[1]], CI1 = w_test$conf.int[1], CI2 = w_test$conf.int[2])

w_test = wilcox.test(data$GRNBoost2, conf.level=0.95, conf.int=TRUE)
outp3 = c(pos = 3, estimate = w_test$estimate[[1]], CI1 = w_test$conf.int[1], CI2 = w_test$conf.int[2])

w_test = wilcox.test(data$PIDC, conf.level=0.95, conf.int=TRUE)
outp4 = c(pos = 4, estimate = w_test$estimate[[1]], CI1 = w_test$conf.int[1], CI2 = w_test$conf.int[2])

df = as.data.frame(t(Reduce(cbind, list(outp1, outp2, outp3, outp4))))
rownames(df) = 1:4
df$method = factor(x = c("scMINER", "GENIE3", "GRNBoost2", "PIDC"), levels = c("scMINER", "GENIE3", "GRNBoost2", "PIDC"))

bar_start = 1.05*max(df$CI2)
bar_inc = 0.05*bar_start
data_melt = reshape::melt(data, variable_name = "method")
methods = as.vector(data_melt$method)
methods[methods == "scMINER_pos"] = "scMINER"
methods[methods == "scMINER_neg"] = "scMINER"
methods = factor(x = methods, levels = c("scMINER", "GENIE3", "GRNBoost2", "PIDC"))
levels(methods) <- c("scMINER", "GENIE3", "GRNBoost2", "PIDC")
data_melt$method = methods

stat.test <- data_melt %>% wilcox_test(value ~ method, paired = FALSE)
stat.test <- stat.test %>% add_xy_position(x = "method")
stat.test$y.position = bar_start + c(0, 1, 2, 3, 4, 5)*bar_inc
stat.test <- stat.test[c(1, 2, 3), ]


p <- ggplot(df, aes(x=method, y=estimate)) +
  geom_bar(aes(fill=method), stat = "identity") +
  geom_errorbar(aes(ymin = CI1, ymax = CI2), width = 0.1) + 
  #theme_linedraw(base_size = 16) + 
  theme_classic(base_size = 16) + 
  stat_pvalue_manual(stat.test, label = "p.adj.signif", tip.length = 0.01) +
  scale_fill_manual(name = 'Method',
                    values = c("scMINER" = "red", "GENIE3" = "green", "GRNBoost2" = "blue", "PIDC" = "sandybrown")) + 
  xlab("") + ylab("|NES|") + 
  ggtitle(paste0("GSEA, NES, ", "TF")) + theme(legend.position = "none") + 
  scale_x_discrete(guide = guide_axis(angle = 45))
p
```



```{r}
save_file = file.path(save_fold, paste0("TF_GSEA_abs_NES_barplot_combine_pos_neg", ".png"))
png(save_file, height=6, width=5, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("TF_GSEA_abs_NES_barplot_combine_pos_neg", ".pdf"))
pdf(save_file, height=6, width=5)
p
dev.off()
```
