---
title: "plot_results"
output: html_document
date: "2024-05-30"
---


```{r}
rm(list = ls())
```

```{r}
set.seed(100) 
```

```{r}
library(Seurat)
library(NetBID2)
library(ggplot2)
library(gridExtra)
library(cowplot)
library(grid)
library(dplyr)
library(scMINER)
library(patchwork)
library(gplots)
library(DropletUtils)
library(scater)
library(scran)
library(SingleCellExperiment)
library(AnnotationDbi)
library(org.Hs.eg.db)
library(EnsDb.Hsapiens.v86)
library(EnsDb.Mmusculus.v79)
library(hrbrthemes)
library(ggpubr)
library(rstatix)
library(reshape)
library(RColorBrewer)
#display.brewer.all()
library(pals)
library(SingleR)
library(pheatmap)
library(igraph)
library(ggraph)
library(graphlayouts)
library(ggforce)
library(scDblFinder)
library(anndata)
library(reticulate)
```


```{r}
save_fold = "/Volumes/shladysh/scMINER/figures/scMINER_SCENIC_activity/Tregs_v3/plot"
dir.create(save_fold)

eset_file = "/Volumes/shladysh/scMINER/figures/scMINER_SCENIC_activity/Tregs_v3/data/eset_QCed.Rdata"
load(eset_file)
eset_cpm = eset_combined_log2
cell_ids = colnames(eset_cpm)

network_file = "/Volumes/shladysh/scMINER/figures/scMINER_SCENIC_activity/Tregs_v3/data/networks_and_regulons.Rdata"
load(network_file)

activity_file = "/Volumes/shladysh/scMINER/figures/scMINER_SCENIC_activity/Tregs_v3/data/scMINER_per_cell_type_activity_mean_netbid.Rdata"
load(activity_file)
eset_tf_ac_sing = eset_tf_ac[,cell_ids]
eset_sig_ac_sing = eset_sig_ac[,cell_ids]
eset_merge_ac_sing = eset_merge_ac[,cell_ids]

glob_act_file = "/Volumes/shladysh/scMINER/figures/scMINER_SCENIC_activity/Tregs_v3/data/scMINER_supercell_global_activity_netbid_mean.Rdata"
load(glob_act_file)
eset_merge_ac_sup = eset_merge_ac[,cell_ids]

scenic_auc_file = "/Volumes/shladysh/scMINER/figures/scMINER_SCENIC_activity/Tregs_v3/data/SCENIC_eset.RData"
load(scenic_auc_file)
eset_scenic_auc = eset_scenic_auc[,cell_ids]
eset_scenic_auc_std = eset_scenic_auc_std[,cell_ids]

mica_expr_file = "/Volumes/shladysh/scMINER/figures/scMINER_SCENIC_activity/Tregs_v3/data/expression_based_clustering_UMAP_euclidean_20_7.38906.txt"
mica_expr_data <- read.table(mica_expr_file, sep = '\t', header = TRUE)
rownames(mica_expr_data) <- mica_expr_data$ID
mica_expr_data <- mica_expr_data[cell_ids,]

mica_act_scMINER_file = "/Volumes/shladysh/scMINER/figures/scMINER_SCENIC_activity/Tregs_v3/data/scMINER_activity_based_clustering_UMAP_euclidean_20_7.5.txt"
mica_act_scMINER_data <- read.table(mica_act_scMINER_file, sep = '\t', header = TRUE)
rownames(mica_act_scMINER_data) <- mica_act_scMINER_data$ID
mica_act_scMINER_data <- mica_act_scMINER_data[cell_ids,]

mica_act_SCENIC_file = "/Volumes/shladysh/scMINER/figures/scMINER_SCENIC_activity/Tregs_v3/data/SCENIC_activity_based_clustering_UMAP_euclidean_20_5.5.txt"
mica_act_SCENIC_data <- read.table(mica_act_SCENIC_file, sep = '\t', header = TRUE)
rownames(mica_act_SCENIC_data) <- mica_act_SCENIC_data$ID
mica_act_SCENIC_data <- mica_act_SCENIC_data[cell_ids,]
```


```{r}
ac_tf_sing = exprs(eset_tf_ac_sing)[,cell_ids]
#for (i in 1:dim(ac_tf_sing)[2]){
#  ac_tf_sing[is.na(ac_tf_sing[,i]),i] = min(ac_tf_sing[!is.na(ac_tf_sing[,i]),i])
#}
ac_tf_sing[is.na(ac_tf_sing)] = min(ac_tf_sing[!is.na(ac_tf_sing)])
row_mean <- rowMeans(ac_tf_sing)
row_stdev <- apply(ac_tf_sing, 1, sd, na.rm=TRUE)
ac_tf_sing_row_norm <- (ac_tf_sing - row_mean)/row_stdev


ac_sig_sing = exprs(eset_sig_ac_sing)[,cell_ids]
#for (i in 1:dim(ac_sig_sing)[2]){
#  ac_sig_sing[is.na(ac_sig_sing[,i]),i] = min(ac_sig_sing[!is.na(ac_sig_sing[,i]),i])
#}
ac_sig_sing[is.na(ac_sig_sing)] = min(ac_sig_sing[!is.na(ac_sig_sing)])
row_mean <- rowMeans(ac_sig_sing)
row_stdev <- apply(ac_sig_sing, 1, sd, na.rm=TRUE)
ac_sig_sing_row_norm <- (ac_sig_sing - row_mean)/row_stdev

ac_all_sing = exprs(eset_merge_ac_sing)[,cell_ids]
#for (i in 1:dim(ac_all_sing)[2]){
#  ac_all_sing[is.na(ac_all_sing[,i]),i] = min(ac_all_sing[!is.na(ac_all_sing[,i]),i])
#}
ac_all_sing[is.na(ac_all_sing)] = min(ac_all_sing[!is.na(ac_all_sing)])
row_mean <- rowMeans(ac_all_sing)
row_stdev <- apply(ac_all_sing, 1, sd, na.rm=TRUE)
ac_all_sing_row_norm <- (ac_all_sing - row_mean)/row_stdev
```



```{r, fig.width = 18, fig.height = 10}
df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                true_label = pData(eset_cpm)$celltype)

axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(5, "cm"))

x_ampl = max(mica_expr_data$X) - min(mica_expr_data$X)
x_min = min(mica_expr_data$X) - 0.05*x_ampl

y_ampl = max(mica_expr_data$Y) - min(mica_expr_data$Y)
y_min = min(mica_expr_data$Y) - 0.05*y_ampl

getPalette = colorRampPalette(brewer.pal(7, "Set2"))
cm = (scales::hue_pal())(4)
df$true_label = factor(df$true_label, levels = c("Spleen", "Lung", "Skin", "VAT"))
p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = true_label)) + geom_point(size = 1) + 
  guides(colour = guide_legend(override.aes = list(size=10), title="True label")) +
  xlab("UMAP 1") + ylab("UMAP 2") +
  theme_void(base_size = 30) + 
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min + 0.18*x_ampl, yend = y_min), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min, yend = y_min + 0.18*y_ampl), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") + 
  annotate("text", x = x_min, y = y_min - 0.01*y_ampl, hjust = 0, vjust = 1, label = "UMAP1", color = "black", size = 8) + 
  annotate("text", x = x_min - 0.01*x_ampl, y = y_min, hjust = 0, vjust = 0, label = "UMAP2", color = "black", size = 8, angle = 90) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.margin = unit(c(0, 0, 0.5, 0.5), "inches"),
        aspect.ratio = 1) +
  scale_color_manual(values = c("Spleen" = cm[1], 
                                "Lung" = cm[2], 
                                "Skin" = cm[3], 
                                "VAT" = cm[4]))

p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_true_label", ".png"))
png(save_file, height=10, width=18, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_true_label", ".pdf"))
pdf(save_file, height=10, width=18)
p
dev.off()
```




```{r, fig.width = 10, fig.height = 10}
df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                true_label = pData(eset_cpm)$celltype)

axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(5, "cm"))

x_ampl = max(mica_expr_data$X) - min(mica_expr_data$X)
x_min = min(mica_expr_data$X) - 0.05*x_ampl

y_ampl = max(mica_expr_data$Y) - min(mica_expr_data$Y)
y_min = min(mica_expr_data$Y) - 0.05*y_ampl

getPalette = colorRampPalette(brewer.pal(7, "Set2"))
cm = (scales::hue_pal())(4)
df$true_label = factor(df$true_label, levels = c("Spleen", "Lung", "Skin", "VAT"))
p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = true_label)) + geom_point(size = 1) + 
  guides(colour = guide_legend(override.aes = list(size=10), title="True label")) +
  xlab("UMAP 1") + ylab("UMAP 2") +
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min + 0.18*x_ampl, yend = y_min), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min, yend = y_min + 0.18*y_ampl), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") + 
  annotate("text", x = x_min, y = y_min - 0.01*y_ampl, hjust = 0, vjust = 1, label = "UMAP1", color = "black", size = 8) + 
  annotate("text", x = x_min - 0.01*x_ampl, y = y_min, hjust = 0, vjust = 0, label = "UMAP2", color = "black", size = 8, angle = 90) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.margin = unit(c(0, 0, 0.5, 0.5), "inches"),
        aspect.ratio = 1) +
  scale_color_manual(values = c("Spleen" = cm[1], 
                                "Lung" = cm[2], 
                                "Skin" = cm[3], 
                                "VAT" = cm[4]))

p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_true_label_no_legend", ".png"))
png(save_file, height=10, width=10, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_true_label_no_legend", ".pdf"))
pdf(save_file, height=10, width=10)
p
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Bach2"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Bach2"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.4) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```




```{r, fig.width = 10, fig.height = 10}
gene = "Klf2"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.7) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Klf2"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.5) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```


```{r, fig.width = 10, fig.height = 10}
gene = "Klf2"
act_vals = as.vector(exprs(eset_scenic_auc[gene,]))
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                Activity = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " SCENIC activity")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.7) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Atf6"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Atf6"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.5) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```


```{r, fig.width = 10, fig.height = 10}
gene = "Atf6b"
act_vals = as.vector(exprs(eset_scenic_auc[gene,]))
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                Activity = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " SCENIC activity")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.7) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```





```{r, fig.width = 10, fig.height = 10}
gene = "Pparg"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Pparg"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.4) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```


```{r, fig.width = 10, fig.height = 10}
gene = "Pparg"
act_vals = as.vector(exprs(eset_scenic_auc[gene,]))
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                Activity = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " SCENIC activity")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.6) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```


```{r, fig.width = 10, fig.height = 10}
gene = "Nr3c1"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Nr3c1"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.5) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```


```{r, fig.width = 10, fig.height = 10}
gene = "Nr3c1"
act_vals = as.vector(exprs(eset_scenic_auc[gene,]))
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                Activity = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " SCENIC activity")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.6) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```




```{r, fig.width = 10, fig.height = 10}
gene = "Rora"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Rora"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.5) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Rara"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Rara"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.5) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```


```{r, fig.width = 10, fig.height = 10}
gene = "Rara"
act_vals = as.vector(exprs(eset_scenic_auc[gene,]))
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                Activity = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " SCENIC activity")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.6) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Rxra"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Rxra"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.5) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```


```{r, fig.width = 10, fig.height = 10}
gene = "Rxra"
act_vals = as.vector(exprs(eset_scenic_auc[gene,]))
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                Activity = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " SCENIC activity")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.6) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Klf3"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Klf3"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.5) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```


```{r, fig.width = 10, fig.height = 10}
gene = "Klf3"
act_vals = as.vector(exprs(eset_scenic_auc[gene,]))
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                Activity = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " SCENIC activity")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.6) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Tcf7"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Tcf7"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.5) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```


```{r, fig.width = 10, fig.height = 10}
gene = "Tcf7l1"
act_vals = as.vector(exprs(eset_scenic_auc[gene,]))
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                Activity = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " SCENIC activity")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.6) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_SCENIC_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Satb1"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.7) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Satb1"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.5) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```





```{r, fig.width = 10, fig.height = 10}
gene = "Notch2"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.7) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Notch2"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.4) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```




```{r, fig.width = 10, fig.height = 10}
gene = "Hlf"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.7) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Hlf"
act_vals = ac_tf_sing[rownames(ac_tf_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.5) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```





```{r, fig.width = 10, fig.height = 10}
gene = "Hells"
exp_vals = exprs(eset_cpm)[rownames(exprs(eset_cpm)) == gene,]
scale_vals = (exp_vals - min(exp_vals))/(max(exp_vals) - min(exp_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                true_label = pData(eset_cpm)$celltype,
                Expression = scale_vals)

p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Expression)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " expression")) +
  scale_color_gradient2(low = "grey80", mid = "blue", high = "blue", midpoint = 0.5) + 
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```



```{r}
save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_expression_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```



```{r, fig.width = 10, fig.height = 10}
gene = "Hells"
act_vals = ac_sig_sing[rownames(ac_sig_sing) == gene, ]
scale_vals = (act_vals - min(act_vals))/(max(act_vals) - min(act_vals))

df = data.frame(UMAP1 = mica_expr_data$X, 
                UMAP2 = mica_expr_data$Y, 
                cell = mica_expr_data$ID, 
                Activity = scale_vals)


p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = Activity)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  ggtitle(paste0(gene, " scMINER activity")) +
  scale_color_gradient2(low = "grey80", mid = "grey80", high = "blue", midpoint = 0.25) +
  theme(plot.title = element_text(hjust = 0.5),
        aspect.ratio = 1)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(p)
dev.off()

save_file = file.path(save_fold, paste0("UMAP_activity_scMINER_single_cells_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(p)
dev.off()
```




```{r, fig.width = 18, fig.height = 10}
df = data.frame(UMAP1 = mica_act_scMINER_data$X, 
                UMAP2 = mica_act_scMINER_data$Y, 
                true_label = pData(eset_cpm)$celltype)

axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(5, "cm"))

x_ampl = max(mica_act_scMINER_data$X) - min(mica_act_scMINER_data$X)
x_min = min(mica_act_scMINER_data$X) - 0.05*x_ampl

y_ampl = max(mica_act_scMINER_data$Y) - min(mica_act_scMINER_data$Y)
y_min = min(mica_act_scMINER_data$Y) - 0.05*y_ampl

getPalette = colorRampPalette(brewer.pal(7, "Set2"))
cm = (scales::hue_pal())(4)
df$true_label = factor(df$true_label, levels = c("Spleen", "Lung", "Skin", "VAT"))
p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = true_label)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  #theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  guides(colour = guide_legend(override.aes = list(size=10), title="True label")) +
  ggtitle(paste0("scMINER activity")) + 
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min + 0.18*x_ampl, yend = y_min), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min, yend = y_min + 0.18*y_ampl), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") + 
  annotate("text", x = x_min, y = y_min - 0.01*y_ampl, hjust = 0, vjust = 1, label = "UMAP1", color = "black", size = 8) + 
  annotate("text", x = x_min - 0.01*x_ampl, y = y_min, hjust = 0, vjust = 0, label = "UMAP2", color = "black", size = 8, angle = 90) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.margin = unit(c(0, 0, 0.5, 0.5), "inches"),
        aspect.ratio = 1) + 
  scale_color_manual(values = c("Spleen" = cm[1], 
                                "Lung" = cm[2], 
                                "Skin" = cm[3], 
                                "VAT" = cm[4]))

cm = (scales::hue_pal())(4)
p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_scMINER_global_network_activity", "_true_label", ".png"))
png(save_file, height=10, width=18, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("UMAP_scMINER_global_network_activity", "_true_label", ".pdf"))
pdf(save_file, height=10, width=18)
p
dev.off()
```


```{r, fig.width = 10, fig.height = 10}
df = data.frame(UMAP1 = mica_act_scMINER_data$X, 
                UMAP2 = mica_act_scMINER_data$Y, 
                true_label = pData(eset_cpm)$celltype)

axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(5, "cm"))

x_ampl = max(mica_act_scMINER_data$X) - min(mica_act_scMINER_data$X)
x_min = min(mica_act_scMINER_data$X) - 0.05*x_ampl

y_ampl = max(mica_act_scMINER_data$Y) - min(mica_act_scMINER_data$Y)
y_min = min(mica_act_scMINER_data$Y) - 0.05*y_ampl

getPalette = colorRampPalette(brewer.pal(7, "Set2"))
cm = (scales::hue_pal())(4)
df$true_label = factor(df$true_label, levels = c("Spleen", "Lung", "Skin", "VAT"))
p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = true_label)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  guides(colour = guide_legend(override.aes = list(size=10), title="True label")) +
  ggtitle(paste0("scMINER activity")) + 
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min + 0.18*x_ampl, yend = y_min), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min, yend = y_min + 0.18*y_ampl), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") + 
  annotate("text", x = x_min, y = y_min - 0.01*y_ampl, hjust = 0, vjust = 1, label = "UMAP1", color = "black", size = 8) + 
  annotate("text", x = x_min - 0.01*x_ampl, y = y_min, hjust = 0, vjust = 0, label = "UMAP2", color = "black", size = 8, angle = 90) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.margin = unit(c(0, 0, 0.5, 0.5), "inches"),
        aspect.ratio = 1) +
  scale_color_manual(values = c("Spleen" = cm[1], 
                                "Lung" = cm[2], 
                                "Skin" = cm[3], 
                                "VAT" = cm[4]))

p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_scMINER_global_network_activity", "_true_label_no_legend", ".png"))
png(save_file, height=10, width=10, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("UMAP_scMINER_global_network_activity", "_true_label_no_legend", ".pdf"))
pdf(save_file, height=10, width=10)
p
dev.off()
```




```{r, fig.width = 12, fig.height = 10}
df = data.frame(UMAP1 = mica_act_scMINER_data$X, 
                UMAP2 = mica_act_scMINER_data$Y, 
                ac_clust = as.character(mica_act_scMINER_data$label))

axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(5, "cm"))

x_ampl = max(mica_act_scMINER_data$X) - min(mica_act_scMINER_data$X)
x_min = min(mica_act_scMINER_data$X) - 0.05*x_ampl

y_ampl = max(mica_act_scMINER_data$Y) - min(mica_act_scMINER_data$Y)
y_min = min(mica_act_scMINER_data$Y) - 0.05*y_ampl

getPalette = colorRampPalette(brewer.pal(7, "Set2"))
p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = ac_clust)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  #theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  guides(colour = guide_legend(override.aes = list(size=10), title="Cluster")) +
  ggtitle(paste0("scMINER activity")) + 
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min + 0.18*x_ampl, yend = y_min), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min, yend = y_min + 0.18*y_ampl), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") + 
  annotate("text", x = x_min, y = y_min - 0.01*y_ampl, hjust = 0, vjust = 1, label = "UMAP1", color = "black", size = 8) + 
  annotate("text", x = x_min - 0.01*x_ampl, y = y_min, hjust = 0, vjust = 0, label = "UMAP2", color = "black", size = 8, angle = 90) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.margin = unit(c(0, 0, 0.5, 0.5), "inches"),
        aspect.ratio = 1)

p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_scMINER_global_network_activity", "_cluster", ".png"))
png(save_file, height=10, width=12, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("UMAP_scMINER_global_network_activity", "_cluster", ".pdf"))
pdf(save_file, height=10, width=12)
p
dev.off()
```



```{r, fig.width = 18, fig.height = 10}
df = data.frame(UMAP1 = mica_act_SCENIC_data$X, 
                UMAP2 = mica_act_SCENIC_data$Y, 
                true_label = pData(eset_cpm)$celltype)

axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(5, "cm"))

x_ampl = max(mica_act_SCENIC_data$X) - min(mica_act_SCENIC_data$X)
x_min = min(mica_act_SCENIC_data$X) - 0.05*x_ampl

y_ampl = max(mica_act_SCENIC_data$Y) - min(mica_act_SCENIC_data$Y)
y_min = min(mica_act_SCENIC_data$Y) - 0.05*y_ampl

getPalette = colorRampPalette(brewer.pal(7, "Set2"))
cm = (scales::hue_pal())(4)
df$true_label = factor(df$true_label, levels = c("Spleen", "Lung", "Skin", "VAT"))
p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = true_label)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  #theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  guides(colour = guide_legend(override.aes = list(size=10), title="True label")) +
  ggtitle("SCENIC activity") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min + 0.18*x_ampl, yend = y_min), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min, yend = y_min + 0.18*y_ampl), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") + 
  annotate("text", x = x_min, y = y_min - 0.01*y_ampl, hjust = 0, vjust = 1, label = "UMAP1", color = "black", size = 8) + 
  annotate("text", x = x_min - 0.01*x_ampl, y = y_min, hjust = 0, vjust = 0, label = "UMAP2", color = "black", size = 8, angle = 90) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.margin = unit(c(0, 0, 0.5, 0.5), "inches"),
        aspect.ratio = 1) +
  scale_color_manual(values = c("Spleen" = cm[1], 
                                "Lung" = cm[2], 
                                "Skin" = cm[3], 
                                "VAT" = cm[4]))

p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_SCENIC_activity", "_true_label", ".png"))
png(save_file, height=10, width=18, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("UMAP_SCENIC_activity", "_true_label", ".pdf"))
pdf(save_file, height=10, width=18)
p
dev.off()
```


```{r, fig.width = 10, fig.height = 10}
df = data.frame(UMAP1 = mica_act_SCENIC_data$X, 
                UMAP2 = mica_act_SCENIC_data$Y, 
                true_label = pData(eset_cpm)$celltype)

axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(5, "cm"))

x_ampl = max(mica_act_SCENIC_data$X) - min(mica_act_SCENIC_data$X)
x_min = min(mica_act_SCENIC_data$X) - 0.05*x_ampl

y_ampl = max(mica_act_SCENIC_data$Y) - min(mica_act_SCENIC_data$Y)
y_min = min(mica_act_SCENIC_data$Y) - 0.05*y_ampl

getPalette = colorRampPalette(brewer.pal(7, "Set2"))
cm = (scales::hue_pal())(4)
df$true_label = factor(df$true_label, levels = c("Spleen", "Lung", "Skin", "VAT"))
p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = true_label)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  guides(colour = guide_legend(override.aes = list(size=10), title="True label")) +
  ggtitle("SCENIC activity") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min + 0.18*x_ampl, yend = y_min), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min, yend = y_min + 0.18*y_ampl), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") + 
  annotate("text", x = x_min, y = y_min - 0.01*y_ampl, hjust = 0, vjust = 1, label = "UMAP1", color = "black", size = 8) + 
  annotate("text", x = x_min - 0.01*x_ampl, y = y_min, hjust = 0, vjust = 0, label = "UMAP2", color = "black", size = 8, angle = 90) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.margin = unit(c(0, 0, 0.5, 0.5), "inches"),
        aspect.ratio = 1) +
  scale_color_manual(values = c("Spleen" = cm[1], 
                                "Lung" = cm[2], 
                                "Skin" = cm[3], 
                                "VAT" = cm[4]))

p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_SCENIC_activity", "_true_label_no_legend", ".png"))
png(save_file, height=10, width=10, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("UMAP_SCENIC_activity", "_true_label_no_legend", ".pdf"))
pdf(save_file, height=10, width=10)
p
dev.off()
```



```{r, fig.width = 12, fig.height = 10}
df = data.frame(UMAP1 = mica_act_SCENIC_data$X, 
                UMAP2 = mica_act_SCENIC_data$Y, 
                ac_clust = as.character(mica_act_SCENIC_data$label))

axis <- ggh4x::guide_axis_truncated(
  trunc_lower = unit(0, "npc"),
  trunc_upper = unit(5, "cm"))

x_ampl = max(mica_act_SCENIC_data$X) - min(mica_act_SCENIC_data$X)
x_min = min(mica_act_SCENIC_data$X) - 0.05*x_ampl

y_ampl = max(mica_act_SCENIC_data$Y) - min(mica_act_SCENIC_data$Y)
y_min = min(mica_act_SCENIC_data$Y) - 0.05*y_ampl


getPalette = colorRampPalette(brewer.pal(7, "Set2"))
p <- ggplot(df, aes(x = UMAP1, y = UMAP2, color = ac_clust)) + geom_point(size = 1) + 
  theme_void(base_size = 30) + 
  #theme(legend.position="none") +
  xlab("UMAP 1") + ylab("UMAP 2") +
  guides(colour = guide_legend(override.aes = list(size=10), title="Cluster")) +
  ggtitle("SCENIC activity") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min + 0.18*x_ampl, yend = y_min), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") +
  geom_segment(aes(x = x_min, y = y_min, 
                   xend = x_min, yend = y_min + 0.18*y_ampl), 
               arrow = arrow(length=unit(.5, 'cm'), type = "closed"), colour = "black") + 
  annotate("text", x = x_min, y = y_min - 0.01*y_ampl, hjust = 0, vjust = 1, label = "UMAP1", color = "black", size = 8) + 
  annotate("text", x = x_min - 0.01*x_ampl, y = y_min, hjust = 0, vjust = 0, label = "UMAP2", color = "black", size = 8, angle = 90) +
  theme(plot.title = element_text(hjust = 0.5),
        plot.margin = unit(c(0, 0, 0.5, 0.5), "inches"),
        aspect.ratio = 1)

p
```


```{r}
save_file = file.path(save_fold, paste0("UMAP_SCENIC_activity", "_cluster", ".png"))
png(save_file, height=10, width=12, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("UMAP_SCENIC_activity", "_cluster", ".pdf"))
pdf(save_file, height=10, width=12)
p
dev.off()
```




```{r}
c1 = pData(eset_cpm)$celltype
c2 = as.character(mica_act_scMINER_data$label)
scMINER_ARI = ARI(c1, c2)

c1 = pData(eset_cpm)$celltype
c2 = as.character(mica_act_SCENIC_data$label)
scenic_ARI = ARI(c1, c2)

c(scMINER_ARI, scenic_ARI)
```



```{r, fig.width=8, fig.height=10}
df = data.frame(method = c("scMINER", "SCENIC"),
                ARI = c(scMINER_ARI, scenic_ARI))

p <- ggplot(data = df, aes(x = method, y = ARI, fill = method)) + geom_bar(stat="identity") + 
  theme_classic(base_size = 40) + xlab("") + ylab("ARI") + theme(legend.position="none") + 
  scale_fill_manual(values=c("blue","red")) + ylim(0, 1.05) + 
  annotate("text", x = 1, y = scenic_ARI + 0.05, hjust = 0.5, label = round(scenic_ARI, digits = 3), color = "black", size = 16) + 
  annotate("text", x = 2, y = scMINER_ARI + 0.05, hjust = 0.5, label = round(scMINER_ARI, digits = 3), color = "black", size = 16)
p
```

```{r}
save_file = file.path(save_fold, paste0("ARI_scMINER_SCENIC", ".png"))
png(save_file, height=10, width=8, units="in", res=200)
p
dev.off()

save_file = file.path(save_fold, paste0("ARI_scMINER_SCENIC", ".pdf"))
pdf(save_file, height=10, width=8)
p
dev.off()
```




```{r}
#TF, Spleen
mk_tf_spleen = c("Tcf7", "Id3", "Bach2")

#TF, Lung
mk_tf_lung = c("Klf2", "Klf3", "Satb1", "Notch2")

#TF, Skin
mk_tf_skin = c("Klf9", "Rxra", "Atf6", "Hlf")

#TF, VAT
mk_tf_vat = c("Pparg", "Atf3", "Atf4", "Fosl2", "Fli1", "Rora", "Nr3c1", "Rara", "Runx2", "Nfil3")


#SIG, Spleen
mk_sig_spleen = c("Capn3", "Gpr83", "Rassf2", "Mgmt", "Inpp5f", "Ddx56", "Lta", "Inpp5b", "Igf1r", "Ephx1")

#SIG, Lung
mk_sig_lung = c("Cxcr4", "Hells", "Ccr7", "Rasgrp2", "Nr4a1", "Cdk1", "Txk", "S100a10", "Trat1", "Stmn1")

#SIG, Skin
mk_sig_skin = c("Chka", "Alg6", "Havcr2", "Gsg2", "Axin2", "Gpr55", "Tnfrsf1a", "Ptafr", "Src", "Gdpd5")
#Gsg2 - not in the list
mk_sig_skin = c("Chka", "Alg6", "Havcr2", "Axin2", "Gpr55", "Tnfrsf1a", "Ptafr", "Src", "Gdpd5")

#SIG, VAT
mk_sig_vat = c("Ctsh", "Ccr1", "Lilr4b", "Adam8", "Ltb4r1", "Lilrb4a", "Irs2", "Il1rl1", "Mmp9", "Dusp14")
mk_sig_vat = c("Ctsh", "Ccr1", "Adam8", "Irs2", "Il1rl1", "Mmp9", "Dusp14")

#Pan-tissue
mk_sig_spleen = c("Capn3", "Gpr83", "Rassf2", "Mgmt", "Inpp5f")
mk_sig_lung = c("Cxcr4", "Hells", "Ccr7", "Rasgrp2", "Txk")
mk_sig_skin = c("Chka", "Havcr2", "Axin2", "Gpr55", "Tnfrsf1a")
mk_sig_vat = c("Ctsh", "Ccr1", "Adam8", "Irs2", "Mmp9")

mk_tf_list = c(mk_tf_spleen, mk_tf_lung, mk_tf_skin, mk_tf_vat)
mk_sig_list = c(mk_sig_spleen, mk_sig_lung, mk_sig_skin, mk_sig_vat)
```



```{r}
all_cell_types = c("Spleen", "Lung", "Skin", "VAT")

ids1 = pData(eset_cpm)$celltype == all_cell_types[1]
ids2 = pData(eset_cpm)$celltype == all_cell_types[2]
ids3 = pData(eset_cpm)$celltype == all_cell_types[3]
ids4 = pData(eset_cpm)$celltype == all_cell_types[4]

true_label_ord = c(pData(eset_cpm)$celltype[ids1], pData(eset_cpm)$celltype[ids2], 
                   pData(eset_cpm)$celltype[ids3], pData(eset_cpm)$celltype[ids4])
cell_id_ord = c(rownames(pData(eset_cpm))[ids1], rownames(pData(eset_cpm))[ids2], 
                rownames(pData(eset_cpm))[ids3], rownames(pData(eset_cpm))[ids4])
exp_all_ord = exprs(eset_cpm)[,cell_id_ord]
```



```{r, fig.width=5, fig.height=5}
genes <- intersect(mk_tf_list, fData(eset_cpm)[, "geneSymbol"])
ids <- match(genes, fData(eset_cpm)[, "geneSymbol"])
exp <- as.matrix(exp_all_ord[ids, ])
row_mean <- rowMeans(exp)
row_stdev <- apply(exp, 1, sd, na.rm=TRUE)
exp <- (exp - row_mean)/row_stdev
rownames(exp) <- genes
df <- data.frame("cell_type" = factor(true_label_ord, levels = unique(true_label_ord)))
ncols <- (scales::hue_pal())(4)
names(ncols) <- unique(true_label_ord)
col_annotation = HeatmapAnnotation(df = df, 
                                   col = list("cell_type" = ncols), 
                                   show_annotation_name = FALSE,
                                   show_legend = TRUE,
                                   annotation_legend_param = list(cell_type = list(title = "Cell type")))
min_col_th = -3
max_col_th = 3
colors = circlize::colorRamp2(c(min_col_th, 0, max_col_th), c("blue", "gray95", "red"))

col_th = max(c(max(exp), abs(min(exp))))
hmp <- Heatmap(exp, col = colors, name = "expression", 
               show_row_names = TRUE, show_column_names = FALSE, cluster_rows = FALSE, 
               cluster_columns = FALSE, top_annotation = col_annotation,
               show_heatmap_legend = TRUE,
               column_title = "Expression TF markers",
               heatmap_legend_param = list(title = "Expression"),
               row_names_side = "left")
hmp
```

```{r}
save_file = file.path(save_fold, "heatmap_expression_TF_markers.png")
png(save_file, height=5, width=5, units="in", res=200)
print(hmp)
dev.off()

save_file = file.path(save_fold, "heatmap_expression_TF_markers.pdf")
pdf(save_file, height=5, width=5)
print(hmp)
dev.off()
```



```{r, fig.width=4.1, fig.height=5}
genes <- intersect(mk_tf_list, fData(eset_cpm)[, "geneSymbol"])
ids <- match(genes, fData(eset_cpm)[, "geneSymbol"])
exp <- as.matrix(exp_all_ord[ids, ])
row_mean <- rowMeans(exp)
row_stdev <- apply(exp, 1, sd, na.rm=TRUE)
exp <- (exp - row_mean)/row_stdev
rownames(exp) <- genes
df <- data.frame("cell_type" = factor(true_label_ord, levels = unique(true_label_ord)))
ncols <- (scales::hue_pal())(4)
names(ncols) <- unique(true_label_ord)
col_annotation = HeatmapAnnotation(df = df, 
                                   col = list("cell_type" = ncols), 
                                   show_annotation_name = FALSE,
                                   show_legend = FALSE,
                                   annotation_legend_param = list(cell_type = list(title = "Cell type", labels = c("Tex progenitor", "Tex intermediate", "Tex terminally exhausted"))))
min_col_th = -3
max_col_th = 3
colors = circlize::colorRamp2(c(min_col_th, 0, max_col_th), c("blue", "gray95", "red"))

col_th = max(c(max(exp), abs(min(exp))))
hmp <- Heatmap(exp, col = colors, name = "expression", 
               show_row_names = TRUE, show_column_names = FALSE, cluster_rows = FALSE, 
               cluster_columns = FALSE, top_annotation = col_annotation,
               show_heatmap_legend = FALSE,
               column_title = "Expression TF markers",
               heatmap_legend_param = list(title = "Expression"),
               row_names_side = "left")
hmp
```

```{r}
save_file = file.path(save_fold, "heatmap_expression_TF_markers_no_legend.png")
png(save_file, height=5, width=4.1, units="in", res=200)
print(hmp)
dev.off()

save_file = file.path(save_fold, "heatmap_expression_TF_markers_no_legend.pdf")
pdf(save_file, height=5, width=4.1)
print(hmp)
dev.off()
```



```{r, fig.width=6, fig.height=6}
genes <- intersect(mk_sig_list, fData(eset_cpm)[, "geneSymbol"])
ids <- match(genes, fData(eset_cpm)[, "geneSymbol"])
exp <- as.matrix(exp_all_ord[ids, ])
row_mean <- rowMeans(exp)
row_stdev <- apply(exp, 1, sd, na.rm=TRUE)
exp <- (exp - row_mean)/row_stdev
rownames(exp) <- genes
df <- data.frame("cell_type" = factor(true_label_ord, levels = unique(true_label_ord)))
ncols <- (scales::hue_pal())(4)
names(ncols) <- unique(true_label_ord)
col_annotation = HeatmapAnnotation(df = df, 
                                   col = list("cell_type" = ncols), 
                                   show_annotation_name = FALSE,
                                   annotation_legend_param = list(cell_type = list(title = "Cell type")))
min_col_th = -3
max_col_th = 3
colors = circlize::colorRamp2(c(min_col_th, 0, max_col_th), c("blue", "gray95", "red"))

col_th = max(c(max(exp), abs(min(exp))))
hmp <- Heatmap(exp, col = colors, name = "expression", 
                 show_row_names = TRUE, show_column_names = FALSE, cluster_rows = FALSE, 
                 cluster_columns = FALSE, top_annotation = col_annotation,
                 column_title = "Expression SIG markers",
                 heatmap_legend_param = list(title = "Expression"))
hmp
```

```{r}
save_file = file.path(save_fold, "heatmap_expression_SIG_markers.png")
png(save_file, height=6, width=6, units="in", res=200)
print(hmp)
dev.off()

save_file = file.path(save_fold, "heatmap_expression_SIG_markers.pdf")
pdf(save_file, height=6, width=6)
print(hmp)
dev.off()
```



```{r, fig.width=5.72, fig.height=7}
genes <- intersect(mk_sig_list, fData(eset_cpm)[, "geneSymbol"])
ids <- match(genes, fData(eset_cpm)[, "geneSymbol"])
exp <- as.matrix(exp_all_ord[ids, ])
row_mean <- rowMeans(exp)
row_stdev <- apply(exp, 1, sd, na.rm=TRUE)
exp <- (exp - row_mean)/row_stdev
rownames(exp) <- genes
df <- data.frame("cell_type" = factor(true_label_ord, levels = unique(true_label_ord)))
ncols <- (scales::hue_pal())(4)
names(ncols) <- unique(true_label_ord)
col_annotation = HeatmapAnnotation(df = df, 
                                   col = list("cell_type" = ncols), 
                                   show_annotation_name = FALSE,
                                   show_legend = FALSE,
                                   annotation_legend_param = list(cell_type = list(title = "Cell type")))
min_col_th = -3
max_col_th = 3
colors = circlize::colorRamp2(c(min_col_th, 0, max_col_th), c("blue", "gray95", "red"))

col_th = max(c(max(exp), abs(min(exp))))
hmp <- Heatmap(exp, col = colors, name = "expression", 
               show_heatmap_legend = FALSE,
               show_row_names = TRUE, show_column_names = FALSE, cluster_rows = FALSE, 
               cluster_columns = FALSE, top_annotation = col_annotation,
               column_title = "Expression SIG markers",
               column_title_gp = gpar(fontsize = 20),
               heatmap_legend_param = list(title = "Expression"),
               row_names_side = "left")
hmp
```


```{r}
save_file = file.path(save_fold, "heatmap_expression_SIG_markers_no_legend.png")
png(save_file, height=7, width=5.72, units="in", res=200)
print(hmp)
dev.off()

save_file = file.path(save_fold, "heatmap_expression_SIG_markers_no_legend.pdf")
pdf(save_file, height=7, width=5.72)
print(hmp)
dev.off()
```






```{r, fig.width=5, fig.height=5}
ids <- match(mk_tf_list, fData(eset_tf_ac_sing)[, "geneSymbol"])
exp <- ac_tf_sing_row_norm[ids, cell_id_ord]
rownames(exp) <- mk_tf_list
df <- data.frame("cell_type" = factor(true_label_ord, levels = unique(true_label_ord)))
n <- length(unique(true_label_ord))
ncols <- (scales::hue_pal())(n)
names(ncols) <- unique(true_label_ord)
min_col_th = -3
max_col_th = 3

col_annotation = HeatmapAnnotation(df = df, 
                                   col = list("cell_type" = ncols), 
                                   show_annotation_name = FALSE,
                                   show_legend = TRUE,
                                   annotation_legend_param = list(cell_type = list(title = "Cell type")))
hmp <- Heatmap(exp, col = circlize::colorRamp2(c(min_col_th, 0, max_col_th), c("blue", "gray95", "red")), 
               heatmap_legend_param = list(color_bar = "continuous", title = "Activity"),
               name = "activity", 
               show_heatmap_legend = TRUE,
               show_row_names = TRUE, show_column_names = FALSE, cluster_rows = FALSE, 
               cluster_columns = FALSE, top_annotation = col_annotation,
               column_title = paste0("scMINER activity TF markers"))
hmp
```


```{r}
save_file = file.path(save_fold, "heatmap_activity_TF_markers_scMINER.png")
png(save_file, height=5, width=5, units="in", res=200)
print(hmp)
dev.off()

save_file = file.path(save_fold, "heatmap_activity_TF_markers_scMINER.pdf")
pdf(save_file, height=5, width=5)
print(hmp)
dev.off()
```




```{r, fig.width=3.5, fig.height=5}
ids <- match(mk_tf_list, fData(eset_tf_ac_sing)[, "geneSymbol"])
exp <- ac_tf_sing_row_norm[ids, cell_id_ord]
rownames(exp) <- mk_tf_list
df <- data.frame("cell_type" = factor(true_label_ord, levels = unique(true_label_ord)))
n <- length(unique(true_label_ord))
ncols <- (scales::hue_pal())(n)
names(ncols) <- unique(true_label_ord)
min_col_th = -3
max_col_th = 3

col_annotation = HeatmapAnnotation(df = df, 
                                   col = list("cell_type" = ncols), 
                                   show_annotation_name = FALSE,
                                   show_legend = FALSE,
                                   annotation_legend_param = list(cell_type = list(title = "Cell type", labels = c("Tpex", "Teff-like", "Tex"))))
hmp <- Heatmap(exp, col = circlize::colorRamp2(c(min_col_th, 0, max_col_th), c("blue", "gray95", "red")), 
               heatmap_legend_param = list(color_bar = "continuous", title = "Activity"),
               name = "activity", 
               show_heatmap_legend = FALSE,
               show_row_names = FALSE, show_column_names = FALSE, cluster_rows = FALSE, 
               cluster_columns = FALSE, top_annotation = col_annotation,
               column_title = paste0("scMINER activity TF markers"))
hmp
```


```{r}
save_file = file.path(save_fold, "heatmap_activity_TF_markers_scMINER_no_legend.png")
png(save_file, height=5, width=3.5, units="in", res=200)
print(hmp)
dev.off()

save_file = file.path(save_fold, "heatmap_activity_TF_markers_scMINER_no_legend.pdf")
pdf(save_file, height=5, width=3.5)
print(hmp)
dev.off()
```





```{r, fig.width=6, fig.height=7}
ids <- match(mk_sig_list, fData(eset_sig_ac_sing)[, "geneSymbol"])
exp <- ac_sig_sing_row_norm[ids, cell_id_ord]
rownames(exp) <- mk_sig_list
df <- data.frame("cell_type" = factor(true_label_ord, levels = unique(true_label_ord)))
n <- length(unique(true_label_ord))
ncols <- (scales::hue_pal())(n)
names(ncols) <- unique(true_label_ord)
min_col_th = -3
max_col_th = 3

col_annotation = HeatmapAnnotation(df = df, 
                                   col = list("cell_type" = ncols), 
                                   show_annotation_name = FALSE,
                                   show_legend = TRUE,
                                   annotation_legend_param = list(cell_type = list(title = "Cell type")))
hmp <- Heatmap(exp, col = circlize::colorRamp2(c(min_col_th, 0, max_col_th), c("blue", "gray95", "red")), 
               heatmap_legend_param = list(color_bar = "continuous", title = "Activity"),
               name = "activity", 
               show_heatmap_legend = TRUE,
               show_row_names = TRUE, show_column_names = FALSE, cluster_rows = FALSE, 
               cluster_columns = FALSE, top_annotation = col_annotation,
               column_title = paste0("scMINER activity SIG markers"))
hmp
```


```{r}
save_file = file.path(save_fold, "heatmap_activity_SIG_markers_scMINER.png")
png(save_file, height=7, width=6, units="in", res=200)
print(hmp)
dev.off()

save_file = file.path(save_fold, "heatmap_activity_SIG_markers_scMINER.pdf")
pdf(save_file, height=7, width=6)
print(hmp)
dev.off()
```


```{r, fig.width=5, fig.height=7}
ids <- match(mk_sig_list, fData(eset_sig_ac_sing)[, "geneSymbol"])
exp <- ac_sig_sing_row_norm[ids, cell_id_ord]
rownames(exp) <- mk_sig_list
df <- data.frame("cell_type" = factor(true_label_ord, levels = unique(true_label_ord)))
n <- length(unique(true_label_ord))
ncols <- (scales::hue_pal())(n)
names(ncols) <- unique(true_label_ord)
min_col_th = -3
max_col_th = 3

col_annotation = HeatmapAnnotation(df = df, 
                                   col = list("cell_type" = ncols), 
                                   show_annotation_name = FALSE,
                                   show_legend = FALSE,
                                   annotation_legend_param = list(cell_type = list(title = "Cell type")))
hmp <- Heatmap(exp, col = circlize::colorRamp2(c(min_col_th, 0, max_col_th), c("blue", "gray95", "red")), 
               heatmap_legend_param = list(color_bar = "continuous", title = "Activity"),
               name = "activity", 
               show_heatmap_legend = FALSE,
               show_row_names = FALSE, show_column_names = FALSE, cluster_rows = FALSE, 
               cluster_columns = FALSE, top_annotation = col_annotation,
               column_title = paste0("scMINER activity SIG markers"),
               column_title_gp = gpar(fontsize = 20))
hmp
```


```{r}
save_file = file.path(save_fold, "heatmap_activity_SIG_markers_scMINER_no_legend.png")
png(save_file, height=7, width=5, units="in", res=200)
print(hmp)
dev.off()

save_file = file.path(save_fold, "heatmap_activity_SIG_markers_scMINER_no_legend.pdf")
pdf(save_file, height=7, width=5)
print(hmp)
dev.off()
```






```{r, fig.width=5, fig.height=5}
#score_df = as.data.frame(exprs(eset_scenic_auc))[mk_tf_list,cell_id_ord]
ids = match(mk_tf_list, rownames(eset_scenic_auc))
score_df = as.data.frame(exprs(eset_scenic_auc))[ids,cell_id_ord]
rownames(score_df) <- mk_tf_list
exp <- as.matrix(score_df)
row_mean <- rowMeans(exp)
row_stdev <- apply(exp, 1, sd, na.rm=TRUE)
exp <- (exp - row_mean)/row_stdev

df <- data.frame("cell_type" = factor(true_label_ord, levels = unique(true_label_ord)))
n <- length(unique(true_label_ord))
ncols <- (scales::hue_pal())(n)
names(ncols) <- unique(true_label_ord)
min_col_th = -3
max_col_th = 3

col_annotation = HeatmapAnnotation(df = df, 
                                   col = list("cell_type" = ncols), 
                                   show_annotation_name = FALSE,
                                   show_legend = TRUE,
                                   annotation_legend_param = list(cell_type = list(title = "Cell type")))
hmp <- Heatmap(exp, col = circlize::colorRamp2(c(min_col_th, 0, max_col_th), c("blue", "gray95", "red")), 
               heatmap_legend_param = list(color_bar = "continuous", title = "Activity"),
               name = "activity", 
               show_heatmap_legend = TRUE,
               show_row_names = TRUE, show_column_names = FALSE, cluster_rows = FALSE, 
               cluster_columns = FALSE, top_annotation = col_annotation,
               column_title = paste0("SCENIC activity TF markers"))
hmp
```


```{r}
save_file = file.path(save_fold, "heatmap_activity_TF_markers_SCENIC.png")
png(save_file, height=5, width=5, units="in", res=200)
print(hmp)
dev.off()

save_file = file.path(save_fold, "heatmap_activity_TF_markers_SCENIC.pdf")
pdf(save_file, height=5, width=5)
print(hmp)
dev.off()
```




```{r, fig.width=3.5, fig.height=5}
#score_df = as.data.frame(exprs(eset_scenic_auc))[mk_tf_list,cell_id_ord]
ids = match(mk_tf_list, rownames(eset_scenic_auc))
score_df = as.data.frame(exprs(eset_scenic_auc))[ids,cell_id_ord]
rownames(score_df) <- mk_tf_list
exp <- as.matrix(score_df)
row_mean <- rowMeans(exp)
row_stdev <- apply(exp, 1, sd, na.rm=TRUE)
exp <- (exp - row_mean)/row_stdev

df <- data.frame("cell_type" = factor(true_label_ord, levels = unique(true_label_ord)))
n <- length(unique(true_label_ord))
ncols <- (scales::hue_pal())(n)
names(ncols) <- unique(true_label_ord)
min_col_th = -3
max_col_th = 3

col_annotation = HeatmapAnnotation(df = df, 
                                   col = list("cell_type" = ncols), 
                                   show_annotation_name = FALSE,
                                   show_legend = FALSE,
                                   annotation_legend_param = list(cell_type = list(title = "Cell type", labels = c("Tpex", "Teff-like", "Tex"))))
hmp <- Heatmap(exp, col = circlize::colorRamp2(c(min_col_th, 0, max_col_th), c("blue", "gray95", "red")), 
               heatmap_legend_param = list(color_bar = "continuous", title = "Activity"),
               name = "activity", 
               show_heatmap_legend = FALSE,
               show_row_names = FALSE, show_column_names = FALSE, cluster_rows = FALSE, 
               cluster_columns = FALSE, top_annotation = col_annotation,
               column_title = paste0("SCENIC activity TF markers"))
hmp
```


```{r}
save_file = file.path(save_fold, "heatmap_activity_TF_markers_SCENIC_no_legend.png")
png(save_file, height=5, width=3.5, units="in", res=200)
print(hmp)
dev.off()

save_file = file.path(save_fold, "heatmap_activity_TF_markers_SCENIC_no_legend.pdf")
pdf(save_file, height=5, width=3.5)
print(hmp)
dev.off()
```





```{r}
all_cell_types = c("Spleen", "Lung", "Skin", "VAT")
gene = "Pparg"
```


```{r}
source1 = all_cell_types[1]
net1 = tf.network1$network_dat

source2 = all_cell_types[2]
net2 = tf.network2$network_dat

source3 = all_cell_types[3]
net3 = tf.network3$network_dat

source4 = all_cell_types[4]
net4 = tf.network4$network_dat

targets1 = net1[net1$source == gene,]$target
targets2 = net2[net2$source == gene,]$target
targets3 = net3[net3$source == gene,]$target
targets4 = net4[net4$source == gene,]$target

targets_all = unique(c(targets1, targets2, targets3, targets4))

all_genes = c(source1, source2, source3, source4, targets_all)

mat = matrix(0, nrow = length(all_genes), ncol = length(all_genes))
rownames(mat) <- all_genes
colnames(mat) <- all_genes

mat[1,names(mat[1,]) %in% targets1] = 50
mat[1,names(mat[1,]) %in% intersect(targets1, targets4)] = 30
mat[1,names(mat[1,]) %in% intersect(targets2, targets4)] = 30
mat[1,names(mat[1,]) %in% intersect(targets3, targets4)] = 30
mat[1,names(mat[1,]) %in% intersect(targets1, intersect(targets2, targets4))] = 30
mat[1,names(mat[1,]) %in% intersect(targets1, intersect(targets3, targets4))] = 30
mat[1,names(mat[1,]) %in% intersect(targets2, intersect(targets3, targets4))] = 30
#mat[1,names(mat[1,]) %in% intersect(targets1, intersect(targets2, intersect(targets3, targets4)))] = 40

mat[2,names(mat[2,]) %in% targets2] = 50
mat[2,names(mat[2,]) %in% intersect(targets1, targets2)] = 30
mat[2,names(mat[2,]) %in% intersect(targets2, targets3)] = 30
mat[2,names(mat[2,]) %in% intersect(targets2, targets4)] = 30
mat[2,names(mat[2,]) %in% intersect(targets1, intersect(targets2, targets3))] = 20
mat[2,names(mat[2,]) %in% intersect(targets1, intersect(targets2, targets4))] = 30
mat[2,names(mat[2,]) %in% intersect(targets2, intersect(targets3, targets4))] = 20
#mat[2,names(mat[2,]) %in% intersect(targets1, intersect(targets2, intersect(targets3, targets4)))] = 40

mat[3,names(mat[3,]) %in% targets3] = 50
mat[3,names(mat[3,]) %in% intersect(targets1, targets3)] = 30
mat[3,names(mat[3,]) %in% intersect(targets2, targets3)] = 30
mat[3,names(mat[3,]) %in% intersect(targets3, targets4)] = 30
mat[3,names(mat[3,]) %in% intersect(targets1, intersect(targets2, targets3))] = 20
mat[3,names(mat[3,]) %in% intersect(targets1, intersect(targets3, targets4))] = 30
mat[3,names(mat[3,]) %in% intersect(targets2, intersect(targets3, targets4))] = 20
#mat[3,names(mat[3,]) %in% intersect(targets1, intersect(targets2, intersect(targets3, targets4)))] = 40

mat[4,names(mat[4,]) %in% targets4] = 50
mat[4,names(mat[4,]) %in% intersect(targets1, targets4)] = 30
mat[4,names(mat[4,]) %in% intersect(targets2, targets4)] = 30
mat[4,names(mat[4,]) %in% intersect(targets3, targets4)] = 30
mat[4,names(mat[4,]) %in% intersect(targets1, intersect(targets2, targets4))] = 30
mat[4,names(mat[4,]) %in% intersect(targets1, intersect(targets3, targets4))] = 30
mat[4,names(mat[4,]) %in% intersect(targets2, intersect(targets3, targets4))] = 30
#mat[4,names(mat[4,]) %in% intersect(targets1, intersect(targets2, intersect(targets3, targets4)))] = 40

#network <- graph_from_adjacency_matrix(mat , mode='directed', diag=F)
network <- graph_from_adjacency_matrix(mat , mode='directed', diag=F, weighted = TRUE)

V(network)$color = rep("gray", length(all_genes))
V(network)$color[all_genes %in% targets1] = "red"
V(network)$color[all_genes %in% targets2] = "green"
V(network)$color[all_genes %in% targets3] = "blue"
V(network)$color[all_genes %in% targets4] = "orange"
V(network)$color[all_genes %in% intersect(targets1, targets2)] = "magenta"
V(network)$color[all_genes %in% intersect(targets1, targets3)] = "magenta"
V(network)$color[all_genes %in% intersect(targets1, targets4)] = "magenta"
V(network)$color[all_genes %in% intersect(targets2, targets3)] = "magenta"
V(network)$color[all_genes %in% intersect(targets2, targets4)] = "magenta"
V(network)$color[all_genes %in% intersect(targets3, targets4)] = "magenta"


#labels = c("Batf\nprog", "Batf\nint", "Batf\nterm", rep('', length(targets_all)))
labels = c(source1, source2, source3, source4, rep('', length(targets_all)))
```




```{r, fig.width=10, fig.height=10}
l = layout_with_drl(network, dim = 2, options=list(simmer.attraction=0.1))
print(plot(network, 
     layout = l,
     vertex.size = 2,
     width = 100,
     edge.arrow.size=0,
     vertex.label = labels,
     vertex.label.dist = 4,
     vertex.label.cex = 1.5,
     vertex.label.color = "black"))
```


```{r}
save_file = file.path(save_fold, paste0("rewiring_diagram_", gene, ".png"))
png(save_file, height=10, width=10, units="in", res=200)
print(plot(network, 
     layout = l,
     vertex.size = 2,
     width = 100,
     edge.arrow.size=0,
     vertex.label = labels,
     vertex.label.dist = 4,
     vertex.label.cex = 1.5,
     vertex.label.color = "black"))
dev.off()

save_file = file.path(save_fold, paste0("rewiring_diagram_", gene, ".pdf"))
pdf(save_file, height=10, width=10)
print(plot(network, 
     layout = l,
     vertex.size = 2,
     width = 100,
     edge.arrow.size=0,
     vertex.label = labels,
     vertex.label.dist = 4,
     vertex.label.cex = 1.5,
     vertex.label.color = "black"))
dev.off()
```
